a_hexagon: domain::model::TrackData Class Reference
domain::model::TrackData Class Reference final
Input data model for track information.
#include <TrackData.hpp>
Public Member Functions
TrackData () noexcept
TrackData (const TrackData &other)=default
TrackData (TrackData &&other) noexcept=default
TrackData & operator= (const TrackData &other)=default
TrackData & operator= (TrackData &&other) noexcept=default
~TrackData ()=default
int32_t getTrackId () const noexcept
void setTrackId (const int32_t &value)
double getXVelocityECEF () const noexcept
void setXVelocityECEF (const double &value)
double getYVelocityECEF () const noexcept
void setYVelocityECEF (const double &value)
double getZVelocityECEF () const noexcept
void setZVelocityECEF (const double &value)
double getXPositionECEF () const noexcept
void setXPositionECEF (const double &value)
double getYPositionECEF () const noexcept
void setYPositionECEF (const double &value)
double getZPositionECEF () const noexcept
void setZPositionECEF (const double &value)
int64_t getOriginalUpdateTime () const noexcept
void setOriginalUpdateTime (const int64_t &value)
bool isValid () const noexcept
std::vector< uint8_t > serialize () const
bool deserialize (const std::vector< uint8_t > &data) noexcept
std::size_t getSerializedSize () const noexcept
Static Public Attributes
static constexpr const char * MULTICAST_ADDRESS = "239.1.1.1"
static constexpr int PORT = 9000
static constexpr const char * ZMQ_PROTOCOL = "udp"
static constexpr const char * ZMQ_SOCKET_TYPE = "DISH"
static constexpr bool IS_SUBSCRIBER = true
Private Member Functions
void validateTrackId (int32_t value) const
void validatePosition (double value) const
void validateVelocity (double value) const
void validateTimestamp (int64_t value) const
Private Attributes
int32_t trackId_
Unique integer identifier for the track.
double xVelocityECEF_
X-axis velocity in ECEF coordinates (m/s)
double yVelocityECEF_
Y-axis velocity in ECEF coordinates (m/s)
double zVelocityECEF_
Z-axis velocity in ECEF coordinates (m/s)
double xPositionECEF_
X-axis position in ECEF coordinates (meters)
double yPositionECEF_
Y-axis position in ECEF coordinates (meters)
double zPositionECEF_
Z-axis position in ECEF coordinates (meters)
int64_t originalUpdateTime_
Original update time (microseconds)
Detailed Description
Input data model for track information.
This class represents incoming track data containing position, velocity, and timing information in ECEF coordinate system.
Note
MISRA C++ 2023 compliant implementation
Definition at line 34 of file TrackData.hpp.
Constructor & Destructor Documentation
TrackData() [1/3]
domain::model::TrackData::TrackData () explicit noexcept
Definition at line 19 of file TrackData.cpp.
TrackData() [2/3]
domain::model::TrackData::TrackData (const TrackData & other) default
TrackData() [3/3]
domain::model::TrackData::TrackData (TrackData && other) default noexcept
~TrackData()
domain::model::TrackData::~TrackData () default
Member Function Documentation
deserialize()
bool domain::model::TrackData::deserialize (const std::vector< uint8_t > & data) noexcept
Definition at line 165 of file TrackData.cpp.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop(), TEST_F(), TEST_F(), and TEST_F().
getOriginalUpdateTime()
int64_t domain::model::TrackData::getOriginalUpdateTime () const noexcept
Definition at line 59 of file TrackData.cpp.
References originalUpdateTime_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getSerializedSize()
std::size_t domain::model::TrackData::getSerializedSize () const noexcept
Definition at line 129 of file TrackData.cpp.
Referenced by serialize().
getTrackId()
int32_t domain::model::TrackData::getTrackId () const noexcept
Definition at line 31 of file TrackData.cpp.
References trackId_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getXPositionECEF()
double domain::model::TrackData::getXPositionECEF () const noexcept
Definition at line 47 of file TrackData.cpp.
References xPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getXVelocityECEF()
double domain::model::TrackData::getXVelocityECEF () const noexcept
Definition at line 35 of file TrackData.cpp.
References xVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getYPositionECEF()
double domain::model::TrackData::getYPositionECEF () const noexcept
Definition at line 51 of file TrackData.cpp.
References yPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getYVelocityECEF()
double domain::model::TrackData::getYVelocityECEF () const noexcept
Definition at line 39 of file TrackData.cpp.
References yVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getZPositionECEF()
double domain::model::TrackData::getZPositionECEF () const noexcept
Definition at line 55 of file TrackData.cpp.
References zPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getZVelocityECEF()
double domain::model::TrackData::getZVelocityECEF () const noexcept
Definition at line 43 of file TrackData.cpp.
References zVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isValid()
bool domain::model::TrackData::isValid () const noexcept
Definition at line 105 of file TrackData.cpp.
References originalUpdateTime_, trackId_, xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop(), and TEST_F().
operator=() [1/2]
TrackData & domain::model::TrackData::operator= (const TrackData & other) default
operator=() [2/2]
TrackData & domain::model::TrackData::operator= (TrackData && other) default noexcept
serialize()
std::vector< uint8_t > domain::model::TrackData::serialize () const
Definition at line 135 of file TrackData.cpp.
References getSerializedSize(), originalUpdateTime_, trackId_, xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
setOriginalUpdateTime()
void domain::model::TrackData::setOriginalUpdateTime (const int64_t & value)
Definition at line 99 of file TrackData.cpp.
References originalUpdateTime_, and validateTimestamp().
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), and TEST_F().
setTrackId()
void domain::model::TrackData::setTrackId (const int32_t & value)
Definition at line 64 of file TrackData.cpp.
References trackId_, and validateTrackId().
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setXPositionECEF()
void domain::model::TrackData::setXPositionECEF (const double & value)
Definition at line 84 of file TrackData.cpp.
References validatePosition(), and xPositionECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setXVelocityECEF()
void domain::model::TrackData::setXVelocityECEF (const double & value)
Definition at line 69 of file TrackData.cpp.
References validateVelocity(), and xVelocityECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), and TEST_F().
setYPositionECEF()
void domain::model::TrackData::setYPositionECEF (const double & value)
Definition at line 89 of file TrackData.cpp.
References validatePosition(), and yPositionECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), TEST_F(), and TEST_F().
setYVelocityECEF()
void domain::model::TrackData::setYVelocityECEF (const double & value)
Definition at line 74 of file TrackData.cpp.
References validateVelocity(), and yVelocityECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), and TEST_F().
setZPositionECEF()
void domain::model::TrackData::setZPositionECEF (const double & value)
Definition at line 94 of file TrackData.cpp.
References validatePosition(), and zPositionECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), TEST_F(), and TEST_F().
setZVelocityECEF()
void domain::model::TrackData::setZVelocityECEF (const double & value)
Definition at line 79 of file TrackData.cpp.
References validateVelocity(), and zVelocityECEF_.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData(), TrackDataExtrapolatorTest::SetUp(), TrackDataTest::SetUp(), TEST_F(), and TEST_F().
validatePosition()
void domain::model::TrackData::validatePosition (double value) const private
Definition at line 210 of file TrackData.cpp.
Referenced by setXPositionECEF(), setYPositionECEF(), and setZPositionECEF().
validateTimestamp()
void domain::model::TrackData::validateTimestamp (int64_t value) const private
Definition at line 222 of file TrackData.cpp.
Referenced by setOriginalUpdateTime().
validateTrackId()
void domain::model::TrackData::validateTrackId (int32_t value) const private
Definition at line 204 of file TrackData.cpp.
Referenced by setTrackId().
validateVelocity()
void domain::model::TrackData::validateVelocity (double value) const private
Definition at line 216 of file TrackData.cpp.
Referenced by setXVelocityECEF(), setYVelocityECEF(), and setZVelocityECEF().
Member Data Documentation
IS_SUBSCRIBER
constexpr bool domain::model::TrackData::IS_SUBSCRIBER = true static constexpr
Definition at line 43 of file TrackData.hpp.
Referenced by TEST_F().
MULTICAST_ADDRESS
constexpr const char* domain::model::TrackData::MULTICAST_ADDRESS = "239.1.1.1" static constexpr
Definition at line 37 of file TrackData.hpp.
Referenced by TEST_F().
originalUpdateTime_
int64_t domain::model::TrackData::originalUpdateTime_ private
Original update time (microseconds)
Definition at line 113 of file TrackData.hpp.
Referenced by getOriginalUpdateTime(), isValid(), serialize(), and setOriginalUpdateTime().
PORT
constexpr int domain::model::TrackData::PORT = 9000 static constexpr
Definition at line 38 of file TrackData.hpp.
Referenced by TEST_F().
trackId_
int32_t domain::model::TrackData::trackId_ private
Unique integer identifier for the track.
Definition at line 99 of file TrackData.hpp.
Referenced by getTrackId(), isValid(), serialize(), and setTrackId().
xPositionECEF_
double domain::model::TrackData::xPositionECEF_ private
X-axis position in ECEF coordinates (meters)
Definition at line 107 of file TrackData.hpp.
Referenced by getXPositionECEF(), isValid(), serialize(), and setXPositionECEF().
xVelocityECEF_
double domain::model::TrackData::xVelocityECEF_ private
X-axis velocity in ECEF coordinates (m/s)
Definition at line 101 of file TrackData.hpp.
Referenced by getXVelocityECEF(), isValid(), serialize(), and setXVelocityECEF().
yPositionECEF_
double domain::model::TrackData::yPositionECEF_ private
Y-axis position in ECEF coordinates (meters)
Definition at line 109 of file TrackData.hpp.
Referenced by getYPositionECEF(), isValid(), serialize(), and setYPositionECEF().
yVelocityECEF_
double domain::model::TrackData::yVelocityECEF_ private
Y-axis velocity in ECEF coordinates (m/s)
Definition at line 103 of file TrackData.hpp.
Referenced by getYVelocityECEF(), isValid(), serialize(), and setYVelocityECEF().
ZMQ_PROTOCOL
constexpr const char* domain::model::TrackData::ZMQ_PROTOCOL = "udp" static constexpr
Definition at line 39 of file TrackData.hpp.
ZMQ_SOCKET_TYPE
constexpr const char* domain::model::TrackData::ZMQ_SOCKET_TYPE = "DISH" static constexpr
Definition at line 42 of file TrackData.hpp.
Referenced by TEST_F().
zPositionECEF_
double domain::model::TrackData::zPositionECEF_ private
Z-axis position in ECEF coordinates (meters)
Definition at line 111 of file TrackData.hpp.
Referenced by getZPositionECEF(), isValid(), serialize(), and setZPositionECEF().
zVelocityECEF_
double domain::model::TrackData::zVelocityECEF_ private
Z-axis velocity in ECEF coordinates (m/s)
Definition at line 105 of file TrackData.hpp.
Referenced by getZVelocityECEF(), isValid(), serialize(), and setZVelocityECEF().
The documentation for this class was generated from the following files:
a_hexagon/domain/ports/TrackData.hpp
a_hexagon/domain/model/TrackData.cpp