a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/domain/model/TrackDataTest.cpp File Reference
TrackDataTest.cpp File Reference
Unit tests for TrackData model class.
#include <gtest/gtest.h>
#include "domain/ports/TrackData.hpp"
#include <vector>
#include <cstdint>
#include <limits>
Classes
class TrackDataTest
Test fixture for TrackData tests.
Functions
TEST_F (TrackDataTest, DefaultConstructor_CreatesValidObject)
TEST_F (TrackDataTest, CopyConstructor_CopiesAllFields)
TEST_F (TrackDataTest, MoveConstructor_MovesAllFields)
TEST_F (TrackDataTest, SetTrackId_GetTrackId_ReturnsCorrectValue)
TEST_F (TrackDataTest, SetTrackId_NegativeValue_ThrowsException)
TEST_F (TrackDataTest, SetPosition_ECEF_CoordinatesSet)
TEST_F (TrackDataTest, SetVelocity_ECEF_VelocitiesSet)
TEST_F (TrackDataTest, SetOriginalUpdateTime_ValidTimestamp_Set)
TEST_F (TrackDataTest, IsValid_ValidData_ReturnsTrue)
TEST_F (TrackDataTest, IsValid_DefaultConstructed_ChecksValidity)
TEST_F (TrackDataTest, Serialize_ReturnsNonEmptyVector)
TEST_F (TrackDataTest, GetSerializedSize_ReturnsExpectedSize)
TEST_F (TrackDataTest, SerializeDeserialize_RoundTrip_DataPreserved)
TEST_F (TrackDataTest, Deserialize_InvalidSize_ReturnsFalse)
TEST_F (TrackDataTest, Deserialize_EmptyVector_ReturnsFalse)
TEST_F (TrackDataTest, SetTrackId_MaxInt32_Succeeds)
TEST_F (TrackDataTest, SetTrackId_MinInt32_ThrowsException)
TEST_F (TrackDataTest, SetPosition_LargeValues_Succeeds)
TEST_F (TrackDataTest, CopyAssignment_CopiesAllFields)
TEST_F (TrackDataTest, MoveAssignment_MovesAllFields)
TEST_F (TrackDataTest, MulticastAddress_CorrectValue)
TEST_F (TrackDataTest, Port_CorrectValue)
TEST_F (TrackDataTest, SocketType_IsDISH)
TEST_F (TrackDataTest, IsSubscriber_True)
Detailed Description
Unit tests for TrackData model class.
GTest based tests for MISRA C++ 2023 compliant TrackData
Author
a_hexagon Team
Version
1.0
Date
2025
Definition in file TrackDataTest.cpp.
Function Documentation
TEST_F() [1/24]
TEST_F (TrackDataTest , CopyAssignment_CopiesAllFields)
Definition at line 224 of file TrackDataTest.cpp.
References domain::model::TrackData::getTrackId(), and domain::model::TrackData::getXPositionECEF().
TEST_F() [2/24]
TEST_F (TrackDataTest , CopyConstructor_CopiesAllFields)
Definition at line 55 of file TrackDataTest.cpp.
References domain::model::TrackData::getOriginalUpdateTime(), domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getXVelocityECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getYVelocityECEF(), domain::model::TrackData::getZPositionECEF(), and domain::model::TrackData::getZVelocityECEF().
TEST_F() [3/24]
TEST_F (TrackDataTest , DefaultConstructor_CreatesValidObject)
Definition at line 41 of file TrackDataTest.cpp.
References domain::model::TrackData::getOriginalUpdateTime(), domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getXVelocityECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getYVelocityECEF(), domain::model::TrackData::getZPositionECEF(), and domain::model::TrackData::getZVelocityECEF().
TEST_F() [4/24]
TEST_F (TrackDataTest , Deserialize_EmptyVector_ReturnsFalse)
Definition at line 185 of file TrackDataTest.cpp.
References domain::model::TrackData::deserialize().
TEST_F() [5/24]
TEST_F (TrackDataTest , Deserialize_InvalidSize_ReturnsFalse)
Definition at line 176 of file TrackDataTest.cpp.
References domain::model::TrackData::deserialize().
TEST_F() [6/24]
TEST_F (TrackDataTest , GetSerializedSize_ReturnsExpectedSize)
Definition at line 150 of file TrackDataTest.cpp.
TEST_F() [7/24]
TEST_F (TrackDataTest , IsSubscriber_True)
Definition at line 258 of file TrackDataTest.cpp.
References domain::model::TrackData::IS_SUBSCRIBER.
TEST_F() [8/24]
TEST_F (TrackDataTest , IsValid_DefaultConstructed_ChecksValidity)
Definition at line 133 of file TrackDataTest.cpp.
References domain::model::TrackData::isValid().
TEST_F() [9/24]
TEST_F (TrackDataTest , IsValid_ValidData_ReturnsTrue)
Definition at line 129 of file TrackDataTest.cpp.
TEST_F() [10/24]
TEST_F (TrackDataTest , MoveAssignment_MovesAllFields)
Definition at line 232 of file TrackDataTest.cpp.
References domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::setTrackId(), and domain::model::TrackData::setXPositionECEF().
TEST_F() [11/24]
TEST_F (TrackDataTest , MoveConstructor_MovesAllFields)
Definition at line 68 of file TrackDataTest.cpp.
References domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::setTrackId(), and domain::model::TrackData::setXPositionECEF().
TEST_F() [12/24]
TEST_F (TrackDataTest , MulticastAddress_CorrectValue)
Definition at line 246 of file TrackDataTest.cpp.
References domain::model::TrackData::MULTICAST_ADDRESS.
TEST_F() [13/24]
TEST_F (TrackDataTest , Port_CorrectValue)
Definition at line 250 of file TrackDataTest.cpp.
References domain::model::TrackData::PORT.
TEST_F() [14/24]
TEST_F (TrackDataTest , Serialize_ReturnsNonEmptyVector)
Definition at line 143 of file TrackDataTest.cpp.
TEST_F() [15/24]
TEST_F (TrackDataTest , SerializeDeserialize_RoundTrip_DataPreserved)
Definition at line 157 of file TrackDataTest.cpp.
References domain::model::TrackData::deserialize(), domain::model::TrackData::getOriginalUpdateTime(), domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getXVelocityECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getYVelocityECEF(), domain::model::TrackData::getZPositionECEF(), and domain::model::TrackData::getZVelocityECEF().
TEST_F() [16/24]
TEST_F (TrackDataTest , SetOriginalUpdateTime_ValidTimestamp_Set)
Definition at line 118 of file TrackDataTest.cpp.
References domain::model::TrackData::getOriginalUpdateTime(), and domain::model::TrackData::setOriginalUpdateTime().
TEST_F() [17/24]
TEST_F (TrackDataTest , SetPosition_ECEF_CoordinatesSet)
Definition at line 94 of file TrackDataTest.cpp.
References domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getZPositionECEF(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setYPositionECEF(), and domain::model::TrackData::setZPositionECEF().
TEST_F() [18/24]
TEST_F (TrackDataTest , SetPosition_LargeValues_Succeeds)
Definition at line 209 of file TrackDataTest.cpp.
References domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getZPositionECEF(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setYPositionECEF(), and domain::model::TrackData::setZPositionECEF().
TEST_F() [19/24]
TEST_F (TrackDataTest , SetTrackId_GetTrackId_ReturnsCorrectValue)
Definition at line 81 of file TrackDataTest.cpp.
References domain::model::TrackData::getTrackId(), and domain::model::TrackData::setTrackId().
TEST_F() [20/24]
TEST_F (TrackDataTest , SetTrackId_MaxInt32_Succeeds)
Definition at line 196 of file TrackDataTest.cpp.
References domain::model::TrackData::getTrackId(), and domain::model::TrackData::setTrackId().
TEST_F() [21/24]
TEST_F (TrackDataTest , SetTrackId_MinInt32_ThrowsException)
Definition at line 203 of file TrackDataTest.cpp.
References domain::model::TrackData::setTrackId().
TEST_F() [22/24]
TEST_F (TrackDataTest , SetTrackId_NegativeValue_ThrowsException)
Definition at line 88 of file TrackDataTest.cpp.
References domain::model::TrackData::setTrackId().
TEST_F() [23/24]
TEST_F (TrackDataTest , SetVelocity_ECEF_VelocitiesSet)
Definition at line 106 of file TrackDataTest.cpp.
References domain::model::TrackData::getXVelocityECEF(), domain::model::TrackData::getYVelocityECEF(), domain::model::TrackData::getZVelocityECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYVelocityECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [24/24]
TEST_F (TrackDataTest , SocketType_IsDISH)
Definition at line 254 of file TrackDataTest.cpp.
References domain::model::TrackData::ZMQ_SOCKET_TYPE.