a_hexagon: TrackDataExtrapolatorTest Class Reference
TrackDataExtrapolatorTest Class Reference
Test fixture for TrackDataExtrapolator.
Protected Member Functions
void SetUp () override
void TearDown () override
void createExtrapolator ()
Create extrapolator with mock outgoing port.
TrackData createTestTrackData (int32_t trackId)
Create valid test TrackData.
Protected Attributes
std::unique_ptr< MockOutgoingPort > mockOutgoingPort_
MockOutgoingPort * mockOutgoingPortPtr_ {nullptr}
std::unique_ptr< TrackDataExtrapolator > extrapolator_
Detailed Description
Test fixture for TrackDataExtrapolator.
Definition at line 31 of file TrackDataExtrapolatorTest.cpp.
Member Function Documentation
createExtrapolator()
void TrackDataExtrapolatorTest::createExtrapolator () inline protected
Create extrapolator with mock outgoing port.
Definition at line 45 of file TrackDataExtrapolatorTest.cpp.
References extrapolator_, and mockOutgoingPortPtr_.
createTestTrackData()
TrackData TrackDataExtrapolatorTest::createTestTrackData (int32_t trackId) inline protected
Create valid test TrackData.
Definition at line 52 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
SetUp()
void TrackDataExtrapolatorTest::SetUp () inline override protected
Definition at line 33 of file TrackDataExtrapolatorTest.cpp.
References mockOutgoingPort_, and mockOutgoingPortPtr_.
TearDown()
void TrackDataExtrapolatorTest::TearDown () inline override protected
Definition at line 38 of file TrackDataExtrapolatorTest.cpp.
Member Data Documentation
extrapolator_
std::unique_ptr<TrackDataExtrapolator> TrackDataExtrapolatorTest::extrapolator_ protected
Definition at line 67 of file TrackDataExtrapolatorTest.cpp.
Referenced by createExtrapolator().
mockOutgoingPort_
std::unique_ptr<MockOutgoingPort> TrackDataExtrapolatorTest::mockOutgoingPort_ protected
Definition at line 65 of file TrackDataExtrapolatorTest.cpp.
Referenced by SetUp().
mockOutgoingPortPtr_
MockOutgoingPort* TrackDataExtrapolatorTest::mockOutgoingPortPtr_ {nullptr} protected
Definition at line 66 of file TrackDataExtrapolatorTest.cpp.
Referenced by createExtrapolator(), and SetUp().
The documentation for this class was generated from the following file:
/workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/domain/logic/TrackDataExtrapolatorTest.cpp