a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/domain/model/ExtrapTrackDataTest.cpp File Reference
ExtrapTrackDataTest.cpp File Reference
Unit tests for ExtrapTrackData model class.
#include <gtest/gtest.h>
#include "domain/ports/ExtrapTrackData.hpp"
#include <vector>
#include <cstdint>
#include <limits>
Classes
class ExtrapTrackDataTest
Test fixture for ExtrapTrackData tests.
Functions
TEST_F (ExtrapTrackDataTest, DefaultConstructor_CreatesValidObject)
TEST_F (ExtrapTrackDataTest, CopyConstructor_CopiesAllFields)
TEST_F (ExtrapTrackDataTest, MoveConstructor_MovesAllFields)
TEST_F (ExtrapTrackDataTest, SetUpdateTime_GetUpdateTime_ReturnsCorrectValue)
TEST_F (ExtrapTrackDataTest, SetFirstHopSentTime_GetFirstHopSentTime_ReturnsCorrectValue)
TEST_F (ExtrapTrackDataTest, AllTimingFields_CanBeSetAndRetrieved)
TEST_F (ExtrapTrackDataTest, SetPosition_ECEF_CoordinatesSet)
TEST_F (ExtrapTrackDataTest, SetVelocity_ECEF_VelocitiesSet)
TEST_F (ExtrapTrackDataTest, IsValid_ValidData_ReturnsTrue)
TEST_F (ExtrapTrackDataTest, IsValid_DefaultConstructed_ReturnsFalse)
TEST_F (ExtrapTrackDataTest, Serialize_ReturnsNonEmptyVector)
TEST_F (ExtrapTrackDataTest, GetSerializedSize_ReturnsExpectedSize)
TEST_F (ExtrapTrackDataTest, SerializeDeserialize_RoundTrip_DataPreserved)
TEST_F (ExtrapTrackDataTest, Deserialize_InvalidSize_ReturnsFalse)
TEST_F (ExtrapTrackDataTest, Deserialize_EmptyVector_ReturnsFalse)
TEST_F (ExtrapTrackDataTest, TimingFields_MaxInt64_ThrowsException)
TEST_F (ExtrapTrackDataTest, TimingConsistency_UpdateTimeAfterOriginal)
TEST_F (ExtrapTrackDataTest, TimingConsistency_FirstHopBetweenOriginalAndUpdate)
Detailed Description
Unit tests for ExtrapTrackData model class.
GTest based tests for MISRA C++ 2023 compliant ExtrapTrackData
Author
a_hexagon Team
Version
1.0
Date
2025
Definition in file ExtrapTrackDataTest.cpp.
Function Documentation
TEST_F() [1/18]
TEST_F (ExtrapTrackDataTest , AllTimingFields_CanBeSetAndRetrieved)
Definition at line 103 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), and domain::model::ExtrapTrackData::setUpdateTime().
TEST_F() [2/18]
TEST_F (ExtrapTrackDataTest , CopyConstructor_CopiesAllFields)
Definition at line 58 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getTrackId(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::getYPositionECEF(), and domain::model::ExtrapTrackData::getZPositionECEF().
TEST_F() [3/18]
TEST_F (ExtrapTrackDataTest , DefaultConstructor_CreatesValidObject)
Definition at line 43 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getTrackId(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::getXVelocityECEF(), domain::model::ExtrapTrackData::getYPositionECEF(), domain::model::ExtrapTrackData::getYVelocityECEF(), domain::model::ExtrapTrackData::getZPositionECEF(), and domain::model::ExtrapTrackData::getZVelocityECEF().
TEST_F() [4/18]
TEST_F (ExtrapTrackDataTest , Deserialize_EmptyVector_ReturnsFalse)
Definition at line 198 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::deserialize().
TEST_F() [5/18]
TEST_F (ExtrapTrackDataTest , Deserialize_InvalidSize_ReturnsFalse)
Definition at line 189 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::deserialize().
TEST_F() [6/18]
TEST_F (ExtrapTrackDataTest , GetSerializedSize_ReturnsExpectedSize)
Definition at line 161 of file ExtrapTrackDataTest.cpp.
TEST_F() [7/18]
TEST_F (ExtrapTrackDataTest , IsValid_DefaultConstructed_ReturnsFalse)
Definition at line 147 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::isValid().
TEST_F() [8/18]
TEST_F (ExtrapTrackDataTest , IsValid_ValidData_ReturnsTrue)
Definition at line 143 of file ExtrapTrackDataTest.cpp.
TEST_F() [9/18]
TEST_F (ExtrapTrackDataTest , MoveConstructor_MovesAllFields)
Definition at line 70 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getTrackId(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), and domain::model::ExtrapTrackData::setXPositionECEF().
TEST_F() [10/18]
TEST_F (ExtrapTrackDataTest , Serialize_ReturnsNonEmptyVector)
Definition at line 154 of file ExtrapTrackDataTest.cpp.
TEST_F() [11/18]
TEST_F (ExtrapTrackDataTest , SerializeDeserialize_RoundTrip_DataPreserved)
Definition at line 168 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::deserialize(), domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getTrackId(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::getXVelocityECEF(), domain::model::ExtrapTrackData::getYPositionECEF(), domain::model::ExtrapTrackData::getYVelocityECEF(), domain::model::ExtrapTrackData::getZPositionECEF(), and domain::model::ExtrapTrackData::getZVelocityECEF().
TEST_F() [12/18]
TEST_F (ExtrapTrackDataTest , SetFirstHopSentTime_GetFirstHopSentTime_ReturnsCorrectValue)
Definition at line 94 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getFirstHopSentTime(), and domain::model::ExtrapTrackData::setFirstHopSentTime().
TEST_F() [13/18]
TEST_F (ExtrapTrackDataTest , SetPosition_ECEF_CoordinatesSet)
Definition at line 117 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::getYPositionECEF(), domain::model::ExtrapTrackData::getZPositionECEF(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), and domain::model::ExtrapTrackData::setZPositionECEF().
TEST_F() [14/18]
TEST_F (ExtrapTrackDataTest , SetUpdateTime_GetUpdateTime_ReturnsCorrectValue)
Definition at line 85 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getUpdateTime(), and domain::model::ExtrapTrackData::setUpdateTime().
TEST_F() [15/18]
TEST_F (ExtrapTrackDataTest , SetVelocity_ECEF_VelocitiesSet)
Definition at line 129 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getXVelocityECEF(), domain::model::ExtrapTrackData::getYVelocityECEF(), domain::model::ExtrapTrackData::getZVelocityECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
TEST_F() [16/18]
TEST_F (ExtrapTrackDataTest , TimingConsistency_FirstHopBetweenOriginalAndUpdate)
Definition at line 230 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), and domain::model::ExtrapTrackData::setUpdateTime().
TEST_F() [17/18]
TEST_F (ExtrapTrackDataTest , TimingConsistency_UpdateTimeAfterOriginal)
Definition at line 221 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), and domain::model::ExtrapTrackData::setUpdateTime().
TEST_F() [18/18]
TEST_F (ExtrapTrackDataTest , TimingFields_MaxInt64_ThrowsException)
Definition at line 209 of file ExtrapTrackDataTest.cpp.
References domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), and domain::model::ExtrapTrackData::setUpdateTime().