a_hexagon: adapters::AdapterManager Class Reference
adapters::AdapterManager Class Reference
Manages all message pipelines with thread-per-type isolation.
#include <AdapterManager.hpp>
Public Member Functions
AdapterManager ()
Default constructor.
~AdapterManager ()
Destructor - stops all pipelines.
AdapterManager (const AdapterManager &)=delete
AdapterManager & operator= (const AdapterManager &)=delete
AdapterManager (AdapterManager &&)=delete
AdapterManager & operator= (AdapterManager &&)=delete
void registerPipeline (MessagePipeline pipeline)
Register a new message pipeline.
bool startAll ()
Start all registered pipelines.
void stopAll () noexcept
Stop all pipelines gracefully.
std::size_t getPipelineCount () const noexcept
Get number of registered pipelines.
bool isRunning () const noexcept
Check if manager is running.
MessagePipeline * getPipeline (const std::string &name) noexcept
Get pipeline by name.
const MessagePipeline * getPipeline (const std::string &name) const noexcept
Get pipeline by name (const version)
Private Attributes
std::vector< MessagePipeline > pipelines_
Registered pipelines.
std::atomic< bool > running_
Manager running state.
Detailed Description
Manages all message pipelines with thread-per-type isolation.
Provides centralized lifecycle management for all adapters. Each registered pipeline operates independently.
Usage Example:
AdapterManager manager;
MessagePipeline trackPipeline("TrackData", trackInAdapter, trackOutAdapter);
manager.registerPipeline(std::move(trackPipeline));
if (manager.startAll()) {
    // All pipelines running
}
manager.stopAll();
Invariant
pipelines_ contains only valid MessagePipeline objects
running_ reflects actual state of pipelines
Definition at line 66 of file AdapterManager.hpp.
Constructor & Destructor Documentation
AdapterManager() [1/3]
adapters::AdapterManager::AdapterManager () inline
Default constructor.
Postcondition
isRunning() returns false
getPipelineCount() returns 0
Definition at line 73 of file AdapterManager.hpp.
~AdapterManager()
adapters::AdapterManager::~AdapterManager () inline
Destructor - stops all pipelines.
Ensures graceful shutdown of all registered pipelines
Definition at line 79 of file AdapterManager.hpp.
References stopAll().
AdapterManager() [2/3]
adapters::AdapterManager::AdapterManager (const AdapterManager &) delete
AdapterManager() [3/3]
adapters::AdapterManager::AdapterManager (AdapterManager &&) delete
Member Function Documentation
getPipeline() [1/2]
const MessagePipeline * adapters::AdapterManager::getPipeline (const std::string & name) const inline noexcept
Get pipeline by name (const version)
Parameters
name Pipeline name to search for
Returns
Const pointer to pipeline if found, nullptr otherwise
Definition at line 162 of file AdapterManager.hpp.
References pipelines_.
getPipeline() [2/2]
MessagePipeline * adapters::AdapterManager::getPipeline (const std::string & name) inline noexcept
Get pipeline by name.
Parameters
name Pipeline name to search for
Returns
Pointer to pipeline if found, nullptr otherwise
Definition at line 151 of file AdapterManager.hpp.
References pipelines_.
getPipelineCount()
std::size_t adapters::AdapterManager::getPipelineCount () const inline noexcept
Get number of registered pipelines.
Returns
Number of pipelines
Definition at line 134 of file AdapterManager.hpp.
References pipelines_.
Referenced by main(), and TEST_F().
isRunning()
bool adapters::AdapterManager::isRunning () const inline noexcept
Check if manager is running.
Returns
true if running
Definition at line 142 of file AdapterManager.hpp.
References running_.
Referenced by TEST_F().
operator=() [1/2]
AdapterManager & adapters::AdapterManager::operator= (AdapterManager &&) delete
operator=() [2/2]
AdapterManager & adapters::AdapterManager::operator= (const AdapterManager &) delete
registerPipeline()
void adapters::AdapterManager::registerPipeline (MessagePipeline pipeline) inline
Register a new message pipeline.
Parameters
pipeline Pipeline to register (moved)
Precondition
Manager should not be running when registering
Postcondition
getPipelineCount() increases by 1
Definition at line 95 of file AdapterManager.hpp.
References pipelines_.
Referenced by main().
startAll()
bool adapters::AdapterManager::startAll () inline
Start all registered pipelines.
Returns
true if all started successfully, false if any failed
Postcondition
isRunning() returns true if successful
Note
If any pipeline fails to start, previously started pipelines remain running. Call stopAll() for cleanup.
Definition at line 106 of file AdapterManager.hpp.
References pipelines_, and running_.
Referenced by main().
stopAll()
void adapters::AdapterManager::stopAll () inline noexcept
Stop all pipelines gracefully.
Postcondition
isRunning() returns false
All pipeline.isRunning() return false
Definition at line 123 of file AdapterManager.hpp.
References pipelines_, and running_.
Referenced by ~AdapterManager(), and main().
Member Data Documentation
pipelines_
std::vector<MessagePipeline> adapters::AdapterManager::pipelines_ private
Registered pipelines.
Definition at line 169 of file AdapterManager.hpp.
Referenced by getPipeline(), getPipeline(), getPipelineCount(), registerPipeline(), startAll(), and stopAll().
running_
std::atomic<bool> adapters::AdapterManager::running_ private
Manager running state.
Definition at line 170 of file AdapterManager.hpp.
Referenced by isRunning(), startAll(), and stopAll().
The documentation for this class was generated from the following file:
a_hexagon/adapters/common/AdapterManager.hpp