a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/adapters/outgoing/ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp File Reference
ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp File Reference
Unit tests for ExtrapTrackDataZeroMQOutgoingAdapter with DIP compliance.
#include <gtest/gtest.h>
#include <memory>
#include <chrono>
#include <thread>
#include "adapters/outgoing/zeromq/ExtrapTrackDataZeroMQOutgoingAdapter.hpp"
#include "../../mocks/MockMessageSocket.hpp"
#include "domain/ports/ExtrapTrackData.hpp"
Classes
class ExtrapTrackDataZeroMQOutgoingAdapterTest
Test fixture for ExtrapTrackDataZeroMQOutgoingAdapter.
Functions
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Constructor_WithValidSocket_CreatesAdapter)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Start_WithConnectedSocket_StartsSuccessfully)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Start_WhenAlreadyRunning_ReturnsTrue)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Stop_WhenRunning_StopsAdapter)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Stop_WhenNotRunning_DoesNothing)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, Destructor_WhenRunning_StopsGracefully)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_SingleMessage_SendsSuccessfully)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_Vector_SendsAllMessages)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_EmptyVector_SendsNothing)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_WhenNotRunning_DoesNotSend)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_AfterStop_DoesNotSend)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_PreservesTrackId)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_PreservesPosition)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_PreservesVelocity)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_PreservesTimestamps)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_WhenSocketFails_HandlesGracefully)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, SendExtrapTrackData_SetsGroupName)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, HighThroughput_SendsMessagesQuickly)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, ConcurrentSends_AreThreadSafe)
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest, ConcurrentStartStop_IsThreadSafe)
Detailed Description
Unit tests for ExtrapTrackDataZeroMQOutgoingAdapter with DIP compliance.
Tests adapter behavior using MockMessageSocket (no real network) Achieves %95+ code coverage through dependency injection
Author
a_hexagon Team
Version
2.0
Date
2025
Note
MISRA C++ 2023 compliant test implementation
Definition in file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
Function Documentation
TEST_F() [1/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , ConcurrentSends_AreThreadSafe)
Definition at line 367 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [2/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , ConcurrentStartStop_IsThreadSafe)
Definition at line 394 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [3/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Constructor_WithValidSocket_CreatesAdapter)
Definition at line 84 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [4/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Destructor_WhenRunning_StopsGracefully)
Definition at line 129 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [5/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , HighThroughput_SendsMessagesQuickly)
Definition at line 345 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [6/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_AfterStop_DoesNotSend)
Definition at line 194 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [7/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_EmptyVector_SendsNothing)
Definition at line 171 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [8/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_PreservesPosition)
Definition at line 225 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References domain::model::ExtrapTrackData::deserialize(), domain::model::ExtrapTrackData::getXPositionECEF(), domain::model::ExtrapTrackData::getYPositionECEF(), domain::model::ExtrapTrackData::getZPositionECEF(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), domain::model::ExtrapTrackData::setZPositionECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
TEST_F() [9/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_PreservesTimestamps)
Definition at line 281 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References domain::model::ExtrapTrackData::deserialize(), domain::model::ExtrapTrackData::getFirstHopSentTime(), domain::model::ExtrapTrackData::getOriginalUpdateTime(), domain::model::ExtrapTrackData::getUpdateTime(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), domain::model::ExtrapTrackData::setZPositionECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
TEST_F() [10/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_PreservesTrackId)
Definition at line 205 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References domain::model::ExtrapTrackData::deserialize(), and domain::model::ExtrapTrackData::getTrackId().
TEST_F() [11/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_PreservesVelocity)
Definition at line 253 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References domain::model::ExtrapTrackData::deserialize(), domain::model::ExtrapTrackData::getXVelocityECEF(), domain::model::ExtrapTrackData::getYVelocityECEF(), domain::model::ExtrapTrackData::getZVelocityECEF(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), domain::model::ExtrapTrackData::setZPositionECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
TEST_F() [12/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_SetsGroupName)
Definition at line 328 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [13/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_SingleMessage_SendsSuccessfully)
Definition at line 141 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [14/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_Vector_SendsAllMessages)
Definition at line 154 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [15/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_WhenNotRunning_DoesNotSend)
Definition at line 183 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [16/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , SendExtrapTrackData_WhenSocketFails_HandlesGracefully)
Definition at line 311 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [17/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Start_WhenAlreadyRunning_ReturnsTrue)
Definition at line 101 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [18/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Start_WithConnectedSocket_StartsSuccessfully)
Definition at line 92 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [19/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Stop_WhenNotRunning_DoesNothing)
Definition at line 121 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
TEST_F() [20/20]
TEST_F (ExtrapTrackDataZeroMQOutgoingAdapterTest , Stop_WhenRunning_StopsAdapter)
Definition at line 111 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.