a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/utils/LoggerTest.cpp File Reference
LoggerTest.cpp File Reference
Unit tests for Logger utility class.
#include <gtest/gtest.h>
#include "utils/Logger.hpp"
#include <string>
#include <thread>
#include <chrono>
#include <atomic>
Classes
class LoggerTest
Test fixture for Logger tests.
Functions
TEST_F (LoggerTest, Init_DefaultParameters_Success)
TEST_F (LoggerTest, Init_CustomQueueSize_Success)
TEST_F (LoggerTest, Init_MultipleThreads_Success)
TEST_F (LoggerTest, InitWithFile_ValidPath_Success)
TEST_F (LoggerTest, DoubleInit_NoError)
TEST_F (LoggerTest, Shutdown_AfterInit_Success)
TEST_F (LoggerTest, Shutdown_BeforeInit_NoError)
TEST_F (LoggerTest, DoubleShutdown_NoError)
TEST_F (LoggerTest, SetLevel_AllLevels_NoError)
TEST_F (LoggerTest, Trace_ValidMessage_NoThrow)
TEST_F (LoggerTest, Debug_ValidMessage_NoThrow)
TEST_F (LoggerTest, Info_ValidMessage_NoThrow)
TEST_F (LoggerTest, Warn_ValidMessage_NoThrow)
TEST_F (LoggerTest, Error_ValidMessage_NoThrow)
TEST_F (LoggerTest, Critical_ValidMessage_NoThrow)
TEST_F (LoggerTest, Info_WithFormatArgs_NoThrow)
TEST_F (LoggerTest, Debug_WithMultipleArgs_NoThrow)
TEST_F (LoggerTest, LogLatency_ValidParams_NoThrow)
TEST_F (LoggerTest, LogLatency_ZeroLatency_NoThrow)
TEST_F (LoggerTest, LogLatency_LargeLatency_NoThrow)
TEST_F (LoggerTest, LogTrackReceived_ValidParams_NoThrow)
TEST_F (LoggerTest, LogTrackReceived_NegativeId_NoThrow)
TEST_F (LoggerTest, ConcurrentLogging_NoDataRace)
TEST_F (LoggerTest, ConcurrentInitShutdown_NoDeadlock)
TEST_F (LoggerTest, LoggingLatency_UnderThreshold)
TEST_F (LoggerTest, LOG_INFO_Macro_Works)
TEST_F (LoggerTest, LOG_DEBUG_Macro_Works)
TEST_F (LoggerTest, LOG_ERROR_Macro_Works)
TEST_F (LoggerTest, IsInitialized_BeforeInit_ReturnsFalse)
TEST_F (LoggerTest, IsInitialized_AfterInit_ReturnsTrue)
TEST_F (LoggerTest, IsInitialized_AfterShutdown_ReturnsFalse)
TEST_F (LoggerTest, EmptyAppName_NoError)
TEST_F (LoggerTest, VeryLongMessage_NoError)
TEST_F (LoggerTest, SpecialCharacters_NoError)
Detailed Description
Unit tests for Logger utility class.
GTest based tests for async logging functionality
Author
a_hexagon Team
Version
1.0
Date
2025
Definition in file LoggerTest.cpp.
Function Documentation
TEST_F() [1/34]
TEST_F (LoggerTest , ConcurrentInitShutdown_NoDeadlock)
Definition at line 265 of file LoggerTest.cpp.
TEST_F() [2/34]
TEST_F (LoggerTest , ConcurrentLogging_NoDataRace)
Definition at line 243 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [3/34]
TEST_F (LoggerTest , Critical_ValidMessage_NoThrow)
Definition at line 166 of file LoggerTest.cpp.
References utils::Logger::critical(), and utils::Logger::init().
TEST_F() [4/34]
TEST_F (LoggerTest , Debug_ValidMessage_NoThrow)
Definition at line 133 of file LoggerTest.cpp.
References utils::Logger::Debug, utils::Logger::debug(), utils::Logger::init(), and utils::Logger::setLevel().
TEST_F() [5/34]
TEST_F (LoggerTest , Debug_WithMultipleArgs_NoThrow)
Definition at line 184 of file LoggerTest.cpp.
References utils::Logger::Debug, utils::Logger::debug(), utils::Logger::init(), and utils::Logger::setLevel().
TEST_F() [6/34]
TEST_F (LoggerTest , DoubleInit_NoError)
Definition at line 68 of file LoggerTest.cpp.
References utils::Logger::init().
TEST_F() [7/34]
TEST_F (LoggerTest , DoubleShutdown_NoError)
Definition at line 96 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::shutdown().
TEST_F() [8/34]
TEST_F (LoggerTest , EmptyAppName_NoError)
Definition at line 357 of file LoggerTest.cpp.
References utils::Logger::init().
TEST_F() [9/34]
TEST_F (LoggerTest , Error_ValidMessage_NoThrow)
Definition at line 158 of file LoggerTest.cpp.
References utils::Logger::error(), and utils::Logger::init().
TEST_F() [10/34]
TEST_F (LoggerTest , Info_ValidMessage_NoThrow)
Definition at line 142 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [11/34]
TEST_F (LoggerTest , Info_WithFormatArgs_NoThrow)
Definition at line 176 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [12/34]
TEST_F (LoggerTest , Init_CustomQueueSize_Success)
Definition at line 44 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::isInitialized().
TEST_F() [13/34]
TEST_F (LoggerTest , Init_DefaultParameters_Success)
Definition at line 36 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::isInitialized().
TEST_F() [14/34]
TEST_F (LoggerTest , Init_MultipleThreads_Success)
Definition at line 52 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::isInitialized().
TEST_F() [15/34]
TEST_F (LoggerTest , InitWithFile_ValidPath_Success)
Definition at line 60 of file LoggerTest.cpp.
References utils::Logger::initWithFile(), and utils::Logger::isInitialized().
TEST_F() [16/34]
TEST_F (LoggerTest , IsInitialized_AfterInit_ReturnsTrue)
Definition at line 342 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::isInitialized().
TEST_F() [17/34]
TEST_F (LoggerTest , IsInitialized_AfterShutdown_ReturnsFalse)
Definition at line 348 of file LoggerTest.cpp.
References utils::Logger::init(), utils::Logger::isInitialized(), and utils::Logger::shutdown().
TEST_F() [18/34]
TEST_F (LoggerTest , IsInitialized_BeforeInit_ReturnsFalse)
Definition at line 338 of file LoggerTest.cpp.
References utils::Logger::isInitialized().
TEST_F() [19/34]
TEST_F (LoggerTest , LOG_DEBUG_Macro_Works)
Definition at line 319 of file LoggerTest.cpp.
References utils::Logger::Debug, utils::Logger::init(), LOG_DEBUG, and utils::Logger::setLevel().
TEST_F() [20/34]
TEST_F (LoggerTest , LOG_ERROR_Macro_Works)
Definition at line 328 of file LoggerTest.cpp.
References utils::Logger::init(), and LOG_ERROR.
TEST_F() [21/34]
TEST_F (LoggerTest , LOG_INFO_Macro_Works)
Definition at line 311 of file LoggerTest.cpp.
References utils::Logger::init(), and LOG_INFO.
TEST_F() [22/34]
TEST_F (LoggerTest , LoggingLatency_UnderThreshold)
Definition at line 290 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [23/34]
TEST_F (LoggerTest , LogLatency_LargeLatency_NoThrow)
Definition at line 215 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::logLatency().
TEST_F() [24/34]
TEST_F (LoggerTest , LogLatency_ValidParams_NoThrow)
Definition at line 199 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::logLatency().
TEST_F() [25/34]
TEST_F (LoggerTest , LogLatency_ZeroLatency_NoThrow)
Definition at line 207 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::logLatency().
TEST_F() [26/34]
TEST_F (LoggerTest , LogTrackReceived_NegativeId_NoThrow)
Definition at line 233 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::logTrackReceived().
TEST_F() [27/34]
TEST_F (LoggerTest , LogTrackReceived_ValidParams_NoThrow)
Definition at line 225 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::logTrackReceived().
TEST_F() [28/34]
TEST_F (LoggerTest , SetLevel_AllLevels_NoError)
Definition at line 108 of file LoggerTest.cpp.
References utils::Logger::Critical, utils::Logger::Debug, utils::Logger::Error, utils::Logger::Info, utils::Logger::init(), utils::Logger::Off, utils::Logger::setLevel(), utils::Logger::Trace, and utils::Logger::Warn.
TEST_F() [29/34]
TEST_F (LoggerTest , Shutdown_AfterInit_Success)
Definition at line 79 of file LoggerTest.cpp.
References utils::Logger::init(), utils::Logger::isInitialized(), and utils::Logger::shutdown().
TEST_F() [30/34]
TEST_F (LoggerTest , Shutdown_BeforeInit_NoError)
Definition at line 89 of file LoggerTest.cpp.
References utils::Logger::shutdown().
TEST_F() [31/34]
TEST_F (LoggerTest , SpecialCharacters_NoError)
Definition at line 373 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [32/34]
TEST_F (LoggerTest , Trace_ValidMessage_NoThrow)
Definition at line 124 of file LoggerTest.cpp.
References utils::Logger::init(), utils::Logger::setLevel(), utils::Logger::Trace, and utils::Logger::trace().
TEST_F() [33/34]
TEST_F (LoggerTest , VeryLongMessage_NoError)
Definition at line 363 of file LoggerTest.cpp.
References utils::Logger::info(), and utils::Logger::init().
TEST_F() [34/34]
TEST_F (LoggerTest , Warn_ValidMessage_NoThrow)
Definition at line 150 of file LoggerTest.cpp.
References utils::Logger::init(), and utils::Logger::warn().