a_hexagon: domain::logic::TrackDataExtrapolator Class Reference
domain::logic::TrackDataExtrapolator Class Reference
Domain service for extrapolating track data.
#include <TrackDataExtrapolator.hpp>
Public Member Functions
TrackDataExtrapolator (std::unique_ptr< domain::ports::outgoing::IExtrapTrackDataOutgoingPort > outgoingPort)
Constructor with ownership transfer.
TrackDataExtrapolator (domain::ports::outgoing::IExtrapTrackDataOutgoingPort *outgoingPort)
Legacy constructor for backward compatibility.
void processAndForwardTrackData (const domain::model::TrackData &trackData)
Process and forward track data.
void extrapolateTrackData (const TrackData &trackData, double inputFrequency, double outputFrequency)
Extrapolate track data at specified frequencies.
TrackDataExtrapolator (const TrackDataExtrapolator &)=delete
TrackDataExtrapolator & operator= (const TrackDataExtrapolator &)=delete
TrackDataExtrapolator (TrackDataExtrapolator &&)=default
TrackDataExtrapolator & operator= (TrackDataExtrapolator &&)=default
~TrackDataExtrapolator ()=default
Public Member Functions inherited from domain::ports::incoming::ITrackDataIncomingPort
virtual ~ITrackDataIncomingPort ()=default
Virtual destructor for proper cleanup.
Private Attributes
std::unique_ptr< domain::ports::outgoing::IExtrapTrackDataOutgoingPort > outgoingPort_
Outgoing port for sending extrapolated data - MISRA compliant smart pointer.
domain::ports::outgoing::IExtrapTrackDataOutgoingPort * rawOutgoingPort_ = nullptr
Raw pointer for legacy compatibility (non-owning)
Detailed Description
Domain service for extrapolating track data.
Implements ITrackDataIncomingPort for hexagonal architecture
Note
MISRA C++ 2023 compliant implementation
Definition at line 40 of file TrackDataExtrapolator.hpp.
Constructor & Destructor Documentation
TrackDataExtrapolator() [1/4]
domain::logic::TrackDataExtrapolator::TrackDataExtrapolator (std::unique_ptr< domain::ports::outgoing::IExtrapTrackDataOutgoingPort > outgoingPort) explicit
Constructor with ownership transfer.
Parameters
outgoingPort Unique pointer to outgoing port (ownership transferred)
Definition at line 26 of file TrackDataExtrapolator.cpp.
TrackDataExtrapolator() [2/4]
domain::logic::TrackDataExtrapolator::TrackDataExtrapolator (domain::ports::outgoing::IExtrapTrackDataOutgoingPort * outgoingPort) explicit
Legacy constructor for backward compatibility.
Parameters
outgoingPort Raw pointer to outgoing port (non-owning)
Deprecated:
Use unique_ptr constructor instead
Definition at line 32 of file TrackDataExtrapolator.cpp.
TrackDataExtrapolator() [3/4]
domain::logic::TrackDataExtrapolator::TrackDataExtrapolator (const TrackDataExtrapolator &) delete
TrackDataExtrapolator() [4/4]
domain::logic::TrackDataExtrapolator::TrackDataExtrapolator (TrackDataExtrapolator &&) default
~TrackDataExtrapolator()
domain::logic::TrackDataExtrapolator::~TrackDataExtrapolator () default
Member Function Documentation
extrapolateTrackData()
void domain::logic::TrackDataExtrapolator::extrapolateTrackData (const TrackData & trackData, double inputFrequency, double outputFrequency)
Extrapolate track data at specified frequencies.
Parameters
trackData Input track data
inputFrequency Input data frequency (Hz)
outputFrequency Output data frequency (Hz)
Definition at line 38 of file TrackDataExtrapolator.cpp.
References domain::model::TrackData::getOriginalUpdateTime(), domain::model::TrackData::getTrackId(), domain::model::TrackData::getXPositionECEF(), domain::model::TrackData::getXVelocityECEF(), domain::model::TrackData::getYPositionECEF(), domain::model::TrackData::getYVelocityECEF(), domain::model::TrackData::getZPositionECEF(), domain::model::TrackData::getZVelocityECEF(), outgoingPort_, rawOutgoingPort_, domain::ports::outgoing::IExtrapTrackDataOutgoingPort::sendExtrapTrackData(), domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), domain::model::ExtrapTrackData::setZPositionECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
Referenced by processAndForwardTrackData().
operator=() [1/2]
TrackDataExtrapolator & domain::logic::TrackDataExtrapolator::operator= (const TrackDataExtrapolator &) delete
operator=() [2/2]
TrackDataExtrapolator & domain::logic::TrackDataExtrapolator::operator= (TrackDataExtrapolator &&) default
processAndForwardTrackData()
void domain::logic::TrackDataExtrapolator::processAndForwardTrackData (const domain::model::TrackData & trackData) virtual
Process and forward track data.
Parameters
trackData Input track data to process
Implements domain::ports::incoming::ITrackDataIncomingPort.
Definition at line 78 of file TrackDataExtrapolator.cpp.
References extrapolateTrackData().
Member Data Documentation
outgoingPort_
std::unique_ptr<domain::ports::outgoing::IExtrapTrackDataOutgoingPort> domain::logic::TrackDataExtrapolator::outgoingPort_ private
Outgoing port for sending extrapolated data - MISRA compliant smart pointer.
Definition at line 43 of file TrackDataExtrapolator.hpp.
Referenced by extrapolateTrackData().
rawOutgoingPort_
domain::ports::outgoing::IExtrapTrackDataOutgoingPort* domain::logic::TrackDataExtrapolator::rawOutgoingPort_ = nullptr private
Raw pointer for legacy compatibility (non-owning)
Definition at line 46 of file TrackDataExtrapolator.hpp.
Referenced by extrapolateTrackData().
The documentation for this class was generated from the following files:
a_hexagon/domain/logic/TrackDataExtrapolator.hpp
a_hexagon/domain/logic/TrackDataExtrapolator.cpp