a_hexagon: ExtrapTrackDataZeroMQOutgoingAdapterTest Class Reference
ExtrapTrackDataZeroMQOutgoingAdapterTest Class Reference
Test fixture for ExtrapTrackDataZeroMQOutgoingAdapter.
Protected Member Functions
void SetUp () override
void TearDown () override
void createAdapter ()
Create adapter with mock socket (DIP injection)
ExtrapTrackData createTestExtrapTrackData (int32_t trackId)
Create valid test ExtrapTrackData.
Protected Attributes
std::unique_ptr< MockMessageSocket > mockSocket_
MockMessageSocket * mockSocketPtr_ {nullptr}
std::unique_ptr< ExtrapTrackDataZeroMQOutgoingAdapter > adapter_
Detailed Description
Test fixture for ExtrapTrackDataZeroMQOutgoingAdapter.
Definition at line 30 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
Member Function Documentation
createAdapter()
void ExtrapTrackDataZeroMQOutgoingAdapterTest::createAdapter () inline protected
Create adapter with mock socket (DIP injection)
Definition at line 51 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References adapter_, and mockSocket_.
createTestExtrapTrackData()
ExtrapTrackData ExtrapTrackDataZeroMQOutgoingAdapterTest::createTestExtrapTrackData (int32_t trackId) inline protected
Create valid test ExtrapTrackData.
Definition at line 60 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References domain::model::ExtrapTrackData::setFirstHopSentTime(), domain::model::ExtrapTrackData::setOriginalUpdateTime(), domain::model::ExtrapTrackData::setTrackId(), domain::model::ExtrapTrackData::setUpdateTime(), domain::model::ExtrapTrackData::setXPositionECEF(), domain::model::ExtrapTrackData::setXVelocityECEF(), domain::model::ExtrapTrackData::setYPositionECEF(), domain::model::ExtrapTrackData::setYVelocityECEF(), domain::model::ExtrapTrackData::setZPositionECEF(), and domain::model::ExtrapTrackData::setZVelocityECEF().
SetUp()
void ExtrapTrackDataZeroMQOutgoingAdapterTest::SetUp () inline override protected
Definition at line 32 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References mockSocket_, and mockSocketPtr_.
TearDown()
void ExtrapTrackDataZeroMQOutgoingAdapterTest::TearDown () inline override protected
Definition at line 42 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
References adapter_.
Member Data Documentation
adapter_
std::unique_ptr<ExtrapTrackDataZeroMQOutgoingAdapter> ExtrapTrackDataZeroMQOutgoingAdapterTest::adapter_ protected
Definition at line 79 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
Referenced by createAdapter(), and TearDown().
mockSocket_
std::unique_ptr<MockMessageSocket> ExtrapTrackDataZeroMQOutgoingAdapterTest::mockSocket_ protected
Definition at line 77 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
Referenced by createAdapter(), and SetUp().
mockSocketPtr_
MockMessageSocket* ExtrapTrackDataZeroMQOutgoingAdapterTest::mockSocketPtr_ {nullptr} protected
Definition at line 78 of file ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
/workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/adapters/outgoing/ExtrapTrackDataZeroMQOutgoingAdapterTest.cpp