a_hexagon: adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter Class Reference
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter Class Reference
Sends ExtrapTrackData via ZeroMQ RADIO socket (UDP multicast)
#include <ExtrapTrackDataZeroMQOutgoingAdapter.hpp>
Public Member Functions
ExtrapTrackDataZeroMQOutgoingAdapter (std::unique_ptr< adapters::common::messaging::IMessageSocket > socket)
Construct adapter with DIP - socket injection (preferred for testing)
ExtrapTrackDataZeroMQOutgoingAdapter ()
Default constructor (legacy - creates ZeroMQ socket internally)
~ExtrapTrackDataZeroMQOutgoingAdapter () override
Destructor - ensures graceful shutdown.
bool start () override
Start the adapter.
void stop () override
Stop the adapter gracefully.
bool isRunning () const override
Check if adapter is running.
std::string getName () const noexcept override
Get adapter name.
void sendExtrapTrackData (const std::vector< domain::model::ExtrapTrackData > &data) override
Send vector of ExtrapTrackData.
void sendExtrapTrackData (const domain::model::ExtrapTrackData &data) override
Send single ExtrapTrackData.
bool isReady () const noexcept
Check if the outgoing connection is ready.
ExtrapTrackDataZeroMQOutgoingAdapter (const ExtrapTrackDataZeroMQOutgoingAdapter &)=delete
ExtrapTrackDataZeroMQOutgoingAdapter & operator= (const ExtrapTrackDataZeroMQOutgoingAdapter &)=delete
ExtrapTrackDataZeroMQOutgoingAdapter (ExtrapTrackDataZeroMQOutgoingAdapter &&)=delete
ExtrapTrackDataZeroMQOutgoingAdapter & operator= (ExtrapTrackDataZeroMQOutgoingAdapter &&)=delete
Public Member Functions inherited from adapters::IAdapter
virtual ~IAdapter ()=default
Virtual destructor for proper cleanup.
Public Member Functions inherited from domain::ports::outgoing::IExtrapTrackDataOutgoingPort
virtual ~IExtrapTrackDataOutgoingPort ()=default
Virtual destructor for proper cleanup.
Private Member Functions
void loadConfiguration ()
Load configuration (for legacy constructor)
bool initializeSocket ()
Initialize socket (for legacy constructor)
void publisherWorker ()
Background worker thread for message transmission.
void enqueueMessage (const domain::model::ExtrapTrackData &data)
Enqueue message for transmission (non-blocking ~20ns)
Private Attributes
std::string endpoint_
ZeroMQ endpoint.
std::string group_
ZeroMQ group name for RADIO.
std::unique_ptr< adapters::common::messaging::IMessageSocket > socket_
Socket abstraction.
std::atomic< bool > running_
Running state flag.
std::atomic< bool > ready_
Ready to send flag.
bool ownsSocket_ {false}
Flag to track socket ownership.
std::thread publisherThread_
Background publisher thread.
std::queue< domain::model::ExtrapTrackData > messageQueue_
Message queue.
std::mutex queueMutex_
Queue protection mutex.
std::condition_variable queueCV_
Queue notification.
Static Private Attributes
static constexpr int32_t REALTIME_THREAD_PRIORITY {80}
SCHED_FIFO priority.
static constexpr int32_t DEDICATED_CPU_CORE {2}
CPU affinity core.
static constexpr std::size_t MAX_QUEUE_SIZE {1000}
Max queue size before drop.
static constexpr const char * DEFAULT_ENDPOINT {"tcp://127.0.0.1:15001"}
static constexpr const char * DEFAULT_GROUP {"ExtrapTrackData"}
Group name for RADIO socket.
Additional Inherited Members
Protected Member Functions inherited from adapters::IAdapter
IAdapter ()=default
Protected default constructor.
IAdapter (const IAdapter &)=default
Protected copy constructor.
IAdapter (IAdapter &&)=default
Protected move constructor.
IAdapter & operator= (const IAdapter &)=default
Protected copy assignment.
IAdapter & operator= (IAdapter &&)=default
Protected move assignment.
Protected Member Functions inherited from domain::ports::outgoing::IExtrapTrackDataOutgoingPort
IExtrapTrackDataOutgoingPort ()=default
Protected default constructor.
IExtrapTrackDataOutgoingPort (const IExtrapTrackDataOutgoingPort &)=default
Protected copy constructor.
IExtrapTrackDataOutgoingPort (IExtrapTrackDataOutgoingPort &&)=default
Protected move constructor.
IExtrapTrackDataOutgoingPort & operator= (const IExtrapTrackDataOutgoingPort &)=default
Protected copy assignment operator.
IExtrapTrackDataOutgoingPort & operator= (IExtrapTrackDataOutgoingPort &&)=default
Protected move assignment operator.
Detailed Description
Sends ExtrapTrackData via ZeroMQ RADIO socket (UDP multicast)
Implements both IAdapter (for lifecycle management) and IExtrapTrackDataOutgoingPort (for domain service integration). Uses background worker thread for non-blocking sends (~20ns enqueue).
Thread Safety:
Uses mutex-protected queue for thread-safe message passing
Background worker thread handles actual ZMQ transmission
Non-blocking sendExtrapTrackData() for real-time performance
Class Invariants:
When running_, socket is connected and ready to send
Definition at line 65 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Constructor & Destructor Documentation
ExtrapTrackDataZeroMQOutgoingAdapter() [1/4]
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ExtrapTrackDataZeroMQOutgoingAdapter (std::unique_ptr< adapters::common::messaging::IMessageSocket > socket) explicit
Construct adapter with DIP - socket injection (preferred for testing)
Parameters
socket Message socket abstraction (ZeroMQ or Mock)
Precondition
socket is not null
Postcondition
Adapter is configured but not started
Definition at line 35 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References LOG_INFO.
ExtrapTrackDataZeroMQOutgoingAdapter() [2/4]
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ExtrapTrackDataZeroMQOutgoingAdapter ()
Default constructor (legacy - creates ZeroMQ socket internally)
Postcondition
Adapter is configured but not started
Deprecated:
Use socket injection constructor for new code
Definition at line 49 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References loadConfiguration(), and LOG_INFO.
~ExtrapTrackDataZeroMQOutgoingAdapter()
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::~ExtrapTrackDataZeroMQOutgoingAdapter () override
Destructor - ensures graceful shutdown.
Definition at line 61 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References LOG_DEBUG, and stop().
ExtrapTrackDataZeroMQOutgoingAdapter() [3/4]
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ExtrapTrackDataZeroMQOutgoingAdapter (const ExtrapTrackDataZeroMQOutgoingAdapter &) delete
ExtrapTrackDataZeroMQOutgoingAdapter() [4/4]
adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ExtrapTrackDataZeroMQOutgoingAdapter (ExtrapTrackDataZeroMQOutgoingAdapter &&) delete
Member Function Documentation
enqueueMessage()
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::enqueueMessage (const domain::model::ExtrapTrackData & data) private
Enqueue message for transmission (non-blocking ~20ns)
Parameters
data Track data to send
Definition at line 216 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References LOG_WARN, MAX_QUEUE_SIZE, messageQueue_, queueCV_, and queueMutex_.
Referenced by sendExtrapTrackData(), and sendExtrapTrackData().
getName()
std::string adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::getName () const override virtual noexcept
Get adapter name.
Returns
"ExtrapTrackDataZeroMQOutgoingAdapter"
Note
MISRA Rule 15-5-1: noexcept specification
Implements adapters::IAdapter.
Definition at line 185 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
initializeSocket()
bool adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::initializeSocket () private
Initialize socket (for legacy constructor)
Returns
true if successful
Definition at line 74 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References adapters::common::messaging::ZeroMQSocket::Connect, endpoint_, group_, LOG_DEBUG, LOG_ERROR, LOG_INFO, ownsSocket_, adapters::common::messaging::ZeroMQSocket::PUB, and socket_.
Referenced by start().
isReady()
bool adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::isReady () const noexcept
Check if the outgoing connection is ready.
Returns
true if socket is connected and ready to send
Definition at line 181 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References ready_, and running_.
Referenced by sendExtrapTrackData(), and sendExtrapTrackData().
isRunning()
bool adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::isRunning () const override virtual
Check if adapter is running.
Returns
true if adapter is active
Implements adapters::IAdapter.
Definition at line 177 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References running_.
loadConfiguration()
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::loadConfiguration () private
Load configuration (for legacy constructor)
Definition at line 66 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References DEFAULT_ENDPOINT, DEFAULT_GROUP, endpoint_, group_, and LOG_DEBUG.
Referenced by ExtrapTrackDataZeroMQOutgoingAdapter().
operator=() [1/2]
ExtrapTrackDataZeroMQOutgoingAdapter & adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::operator= (const ExtrapTrackDataZeroMQOutgoingAdapter &) delete
operator=() [2/2]
ExtrapTrackDataZeroMQOutgoingAdapter & adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::operator= (ExtrapTrackDataZeroMQOutgoingAdapter &&) delete
publisherWorker()
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::publisherWorker () private
Background worker thread for message transmission.
Runs with real-time priority and CPU affinity
Definition at line 235 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References domain::model::ExtrapTrackData::getTrackId(), group_, LOG_DEBUG, LOG_ERROR, LOG_WARN, messageQueue_, queueCV_, queueMutex_, running_, domain::model::ExtrapTrackData::serialize(), and socket_.
Referenced by start().
sendExtrapTrackData() [1/2]
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::sendExtrapTrackData (const domain::model::ExtrapTrackData & data) override virtual
Send single ExtrapTrackData.
Parameters
data ExtrapTrackData to send
Non-blocking - queues message for background transmission (~20ns)
Implements domain::ports::outgoing::IExtrapTrackDataOutgoingPort.
Definition at line 204 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References enqueueMessage(), domain::model::ExtrapTrackData::getTrackId(), isReady(), and LOG_WARN.
sendExtrapTrackData() [2/2]
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::sendExtrapTrackData (const std::vector< domain::model::ExtrapTrackData > & data) override virtual
Send vector of ExtrapTrackData.
Parameters
data Vector of ExtrapTrackData to send
Implements domain::ports::outgoing::IExtrapTrackDataOutgoingPort.
Definition at line 191 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References enqueueMessage(), isReady(), and LOG_WARN.
start()
bool adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::start () override virtual
Start the adapter.
Returns
true if started successfully
Postcondition
isRunning() returns true
Implements adapters::IAdapter.
Definition at line 110 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References DEDICATED_CPU_CORE, initializeSocket(), LOG_DEBUG, LOG_ERROR, LOG_INFO, LOG_WARN, publisherThread_, publisherWorker(), ready_, REALTIME_THREAD_PRIORITY, running_, and socket_.
stop()
void adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::stop () override virtual
Stop the adapter gracefully.
Postcondition
isRunning() returns false
Implements adapters::IAdapter.
Definition at line 152 of file ExtrapTrackDataZeroMQOutgoingAdapter.cpp.
References LOG_INFO, publisherThread_, queueCV_, ready_, running_, and socket_.
Referenced by ~ExtrapTrackDataZeroMQOutgoingAdapter().
Member Data Documentation
DEDICATED_CPU_CORE
constexpr int32_t adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::DEDICATED_CPU_CORE {2} static constexpr private
CPU affinity core.
Definition at line 190 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by start().
DEFAULT_ENDPOINT
constexpr const char* adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::DEFAULT_ENDPOINT {"tcp://127.0.0.1:15001"} static constexpr private
Definition at line 197 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by loadConfiguration().
DEFAULT_GROUP
constexpr const char* adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::DEFAULT_GROUP {"ExtrapTrackData"} static constexpr private
Group name for RADIO socket.
Definition at line 198 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by loadConfiguration().
endpoint_
std::string adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::endpoint_ private
ZeroMQ endpoint.
Definition at line 170 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by initializeSocket(), and loadConfiguration().
group_
std::string adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::group_ private
ZeroMQ group name for RADIO.
Definition at line 171 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by initializeSocket(), loadConfiguration(), and publisherWorker().
MAX_QUEUE_SIZE
constexpr std::size_t adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::MAX_QUEUE_SIZE {1000} static constexpr private
Max queue size before drop.
Definition at line 191 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by enqueueMessage().
messageQueue_
std::queue<domain::model::ExtrapTrackData> adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::messageQueue_ private
Message queue.
Definition at line 183 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by enqueueMessage(), and publisherWorker().
ownsSocket_
bool adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ownsSocket_ {false} private
Flag to track socket ownership.
Definition at line 179 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by initializeSocket().
publisherThread_
std::thread adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::publisherThread_ private
Background publisher thread.
Definition at line 182 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by start(), and stop().
queueCV_
std::condition_variable adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::queueCV_ private
Queue notification.
Definition at line 185 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by enqueueMessage(), publisherWorker(), and stop().
queueMutex_
std::mutex adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::queueMutex_ mutable private
Queue protection mutex.
Definition at line 184 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by enqueueMessage(), and publisherWorker().
ready_
std::atomic<bool> adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::ready_ private
Ready to send flag.
Definition at line 178 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by isReady(), start(), and stop().
REALTIME_THREAD_PRIORITY
constexpr int32_t adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::REALTIME_THREAD_PRIORITY {80} static constexpr private
SCHED_FIFO priority.
Definition at line 189 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by start().
running_
std::atomic<bool> adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::running_ private
Running state flag.
Definition at line 177 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by isReady(), isRunning(), publisherWorker(), start(), and stop().
socket_
std::unique_ptr<adapters::common::messaging::IMessageSocket> adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::socket_ private
Socket abstraction.
Definition at line 174 of file ExtrapTrackDataZeroMQOutgoingAdapter.hpp.
Referenced by initializeSocket(), publisherWorker(), start(), and stop().
The documentation for this class was generated from the following files:
a_hexagon/adapters/outgoing/zeromq/ExtrapTrackDataZeroMQOutgoingAdapter.hpp
a_hexagon/adapters/outgoing/zeromq/ExtrapTrackDataZeroMQOutgoingAdapter.cpp