a_hexagon: domain::model::ExtrapTrackData Class Reference
domain::model::ExtrapTrackData Class Reference final
Bir izin ECEF koordinat sistemindeki extrapolation yapılmış kinematik durumunu ve detaylı zamanlama bilgilerini içerir.
#include <ExtrapTrackData.hpp>
Public Member Functions
ExtrapTrackData () noexcept
ExtrapTrackData (const ExtrapTrackData &other)=default
ExtrapTrackData (ExtrapTrackData &&other) noexcept=default
ExtrapTrackData & operator= (const ExtrapTrackData &other)=default
ExtrapTrackData & operator= (ExtrapTrackData &&other) noexcept=default
~ExtrapTrackData ()=default
int32_t getTrackId () const noexcept
void setTrackId (const int32_t &value)
double getXVelocityECEF () const noexcept
void setXVelocityECEF (const double &value)
double getYVelocityECEF () const noexcept
void setYVelocityECEF (const double &value)
double getZVelocityECEF () const noexcept
void setZVelocityECEF (const double &value)
double getXPositionECEF () const noexcept
void setXPositionECEF (const double &value)
double getYPositionECEF () const noexcept
void setYPositionECEF (const double &value)
double getZPositionECEF () const noexcept
void setZPositionECEF (const double &value)
int64_t getOriginalUpdateTime () const noexcept
void setOriginalUpdateTime (const int64_t &value)
int64_t getUpdateTime () const noexcept
void setUpdateTime (const int64_t &value)
int64_t getFirstHopSentTime () const noexcept
void setFirstHopSentTime (const int64_t &value)
bool isValid () const noexcept
std::vector< uint8_t > serialize () const
bool deserialize (const std::vector< uint8_t > &data) noexcept
std::size_t getSerializedSize () const noexcept
Static Public Attributes
static constexpr const char * MULTICAST_ADDRESS = "239.1.1.5"
static constexpr int PORT = 9596
static constexpr const char * ZMQ_SOCKET_TYPE = "RADIO"
static constexpr bool IS_PUBLISHER = true
Private Member Functions
void validateTrackId (int32_t value) const
void validateXVelocityECEF (double value) const
void validateYVelocityECEF (double value) const
void validateZVelocityECEF (double value) const
void validateXPositionECEF (double value) const
void validateYPositionECEF (double value) const
void validateZPositionECEF (double value) const
void validateOriginalUpdateTime (int64_t value) const
void validateUpdateTime (int64_t value) const
void validateFirstHopSentTime (int64_t value) const
Private Attributes
int32_t trackId_
İz için benzersiz tam sayı kimliği.
double xVelocityECEF_
ECEF koordinatlarındaki X ekseni hızı (m/s)
double yVelocityECEF_
ECEF koordinatlarındaki Y ekseni hızı (m/s)
double zVelocityECEF_
ECEF koordinatlarındaki Z ekseni hızı (m/s)
double xPositionECEF_
ECEF koordinatlarındaki X ekseni konumu (metre)
double yPositionECEF_
ECEF koordinatlarındaki Y ekseni konumu (metre)
double zPositionECEF_
ECEF koordinatlarındaki Z ekseni konumu (metre)
int64_t originalUpdateTime_
Original güncelleme zamanı (mikrosaniye)
int64_t updateTime_
Son güncelleme zamanı (mikrosaniye)
int64_t firstHopSentTime_
İlk atlamanın gönderildiği zaman (mikrosaniye)
Detailed Description
Bir izin ECEF koordinat sistemindeki extrapolation yapılmış kinematik durumunu ve detaylı zamanlama bilgilerini içerir.
Auto-generated from ExtrapTrackData.json MISRA C++ 2023 compliant implementation Direction: outgoing
Definition at line 20 of file ExtrapTrackData.hpp.
Constructor & Destructor Documentation
ExtrapTrackData() [1/3]
domain::model::ExtrapTrackData::ExtrapTrackData () explicit noexcept
Definition at line 7 of file ExtrapTrackData.cpp.
References firstHopSentTime_, originalUpdateTime_, trackId_, updateTime_, xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
ExtrapTrackData() [2/3]
domain::model::ExtrapTrackData::ExtrapTrackData (const ExtrapTrackData & other) default
ExtrapTrackData() [3/3]
domain::model::ExtrapTrackData::ExtrapTrackData (ExtrapTrackData && other) default noexcept
~ExtrapTrackData()
domain::model::ExtrapTrackData::~ExtrapTrackData () default
Member Function Documentation
deserialize()
bool domain::model::ExtrapTrackData::deserialize (const std::vector< uint8_t > & data) noexcept
Definition at line 256 of file ExtrapTrackData.cpp.
Referenced by TEST_F(), TEST_F(), and TEST_F().
getFirstHopSentTime()
int64_t domain::model::ExtrapTrackData::getFirstHopSentTime () const noexcept
Definition at line 161 of file ExtrapTrackData.cpp.
References firstHopSentTime_.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getOriginalUpdateTime()
int64_t domain::model::ExtrapTrackData::getOriginalUpdateTime () const noexcept
Definition at line 143 of file ExtrapTrackData.cpp.
References originalUpdateTime_.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getSerializedSize()
std::size_t domain::model::ExtrapTrackData::getSerializedSize () const noexcept
Definition at line 346 of file ExtrapTrackData.cpp.
References firstHopSentTime_, originalUpdateTime_, trackId_, updateTime_, xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
Referenced by serialize().
getTrackId()
int32_t domain::model::ExtrapTrackData::getTrackId () const noexcept
Definition at line 80 of file ExtrapTrackData.cpp.
References trackId_.
Referenced by adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::sendExtrapTrackData(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getUpdateTime()
int64_t domain::model::ExtrapTrackData::getUpdateTime () const noexcept
Definition at line 152 of file ExtrapTrackData.cpp.
References updateTime_.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getXPositionECEF()
double domain::model::ExtrapTrackData::getXPositionECEF () const noexcept
Definition at line 116 of file ExtrapTrackData.cpp.
References xPositionECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getXVelocityECEF()
double domain::model::ExtrapTrackData::getXVelocityECEF () const noexcept
Definition at line 89 of file ExtrapTrackData.cpp.
References xVelocityECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getYPositionECEF()
double domain::model::ExtrapTrackData::getYPositionECEF () const noexcept
Definition at line 125 of file ExtrapTrackData.cpp.
References yPositionECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getYVelocityECEF()
double domain::model::ExtrapTrackData::getYVelocityECEF () const noexcept
Definition at line 98 of file ExtrapTrackData.cpp.
References yVelocityECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getZPositionECEF()
double domain::model::ExtrapTrackData::getZPositionECEF () const noexcept
Definition at line 134 of file ExtrapTrackData.cpp.
References zPositionECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getZVelocityECEF()
double domain::model::ExtrapTrackData::getZVelocityECEF () const noexcept
Definition at line 107 of file ExtrapTrackData.cpp.
References zVelocityECEF_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
isValid()
bool domain::model::ExtrapTrackData::isValid () const noexcept
Definition at line 170 of file ExtrapTrackData.cpp.
References firstHopSentTime_, originalUpdateTime_, trackId_, updateTime_, validateFirstHopSentTime(), validateOriginalUpdateTime(), validateTrackId(), validateUpdateTime(), validateXPositionECEF(), validateXVelocityECEF(), validateYPositionECEF(), validateYVelocityECEF(), validateZPositionECEF(), validateZVelocityECEF(), xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
Referenced by TEST_F().
operator=() [1/2]
ExtrapTrackData & domain::model::ExtrapTrackData::operator= (const ExtrapTrackData & other) default
operator=() [2/2]
ExtrapTrackData & domain::model::ExtrapTrackData::operator= (ExtrapTrackData && other) default noexcept
serialize()
std::vector< uint8_t > domain::model::ExtrapTrackData::serialize () const
Definition at line 189 of file ExtrapTrackData.cpp.
References firstHopSentTime_, getSerializedSize(), originalUpdateTime_, trackId_, updateTime_, xPositionECEF_, xVelocityECEF_, yPositionECEF_, yVelocityECEF_, zPositionECEF_, and zVelocityECEF_.
Referenced by adapters::outgoing::zeromq::ExtrapTrackDataZeroMQOutgoingAdapter::sendExtrapTrackData().
setFirstHopSentTime()
void domain::model::ExtrapTrackData::setFirstHopSentTime (const int64_t & value)
Definition at line 165 of file ExtrapTrackData.cpp.
References firstHopSentTime_, and validateFirstHopSentTime().
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setOriginalUpdateTime()
void domain::model::ExtrapTrackData::setOriginalUpdateTime (const int64_t & value)
Definition at line 147 of file ExtrapTrackData.cpp.
References originalUpdateTime_, and validateOriginalUpdateTime().
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setTrackId()
void domain::model::ExtrapTrackData::setTrackId (const int32_t & value)
Definition at line 84 of file ExtrapTrackData.cpp.
References trackId_, and validateTrackId().
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), and TEST_F().
setUpdateTime()
void domain::model::ExtrapTrackData::setUpdateTime (const int64_t & value)
Definition at line 156 of file ExtrapTrackData.cpp.
References updateTime_, and validateUpdateTime().
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
setXPositionECEF()
void domain::model::ExtrapTrackData::setXPositionECEF (const double & value)
Definition at line 120 of file ExtrapTrackData.cpp.
References validateXPositionECEF(), and xPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), and TEST_F().
setXVelocityECEF()
void domain::model::ExtrapTrackData::setXVelocityECEF (const double & value)
Definition at line 93 of file ExtrapTrackData.cpp.
References validateXVelocityECEF(), and xVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), and TEST_F().
setYPositionECEF()
void domain::model::ExtrapTrackData::setYPositionECEF (const double & value)
Definition at line 129 of file ExtrapTrackData.cpp.
References validateYPositionECEF(), and yPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), and TEST_F().
setYVelocityECEF()
void domain::model::ExtrapTrackData::setYVelocityECEF (const double & value)
Definition at line 102 of file ExtrapTrackData.cpp.
References validateYVelocityECEF(), and yVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), and TEST_F().
setZPositionECEF()
void domain::model::ExtrapTrackData::setZPositionECEF (const double & value)
Definition at line 138 of file ExtrapTrackData.cpp.
References validateZPositionECEF(), and zPositionECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), and TEST_F().
setZVelocityECEF()
void domain::model::ExtrapTrackData::setZVelocityECEF (const double & value)
Definition at line 111 of file ExtrapTrackData.cpp.
References validateZVelocityECEF(), and zVelocityECEF_.
Referenced by domain::logic::TrackDataExtrapolator::extrapolateTrackData(), ExtrapTrackDataTest::SetUp(), TEST_F(), and TEST_F().
validateFirstHopSentTime()
void domain::model::ExtrapTrackData::validateFirstHopSentTime (int64_t value) const private
Definition at line 74 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setFirstHopSentTime().
validateOriginalUpdateTime()
void domain::model::ExtrapTrackData::validateOriginalUpdateTime (int64_t value) const private
Definition at line 62 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setOriginalUpdateTime().
validateTrackId()
void domain::model::ExtrapTrackData::validateTrackId (int32_t value) const private
Definition at line 20 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setTrackId().
validateUpdateTime()
void domain::model::ExtrapTrackData::validateUpdateTime (int64_t value) const private
Definition at line 68 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setUpdateTime().
validateXPositionECEF()
void domain::model::ExtrapTrackData::validateXPositionECEF (double value) const private
Definition at line 44 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setXPositionECEF().
validateXVelocityECEF()
void domain::model::ExtrapTrackData::validateXVelocityECEF (double value) const private
Definition at line 26 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setXVelocityECEF().
validateYPositionECEF()
void domain::model::ExtrapTrackData::validateYPositionECEF (double value) const private
Definition at line 50 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setYPositionECEF().
validateYVelocityECEF()
void domain::model::ExtrapTrackData::validateYVelocityECEF (double value) const private
Definition at line 32 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setYVelocityECEF().
validateZPositionECEF()
void domain::model::ExtrapTrackData::validateZPositionECEF (double value) const private
Definition at line 56 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setZPositionECEF().
validateZVelocityECEF()
void domain::model::ExtrapTrackData::validateZVelocityECEF (double value) const private
Definition at line 38 of file ExtrapTrackData.cpp.
Referenced by isValid(), and setZVelocityECEF().
Member Data Documentation
firstHopSentTime_
int64_t domain::model::ExtrapTrackData::firstHopSentTime_ private
İlk atlamanın gönderildiği zaman (mikrosaniye)
Definition at line 108 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getFirstHopSentTime(), getSerializedSize(), isValid(), serialize(), and setFirstHopSentTime().
IS_PUBLISHER
constexpr bool domain::model::ExtrapTrackData::IS_PUBLISHER = true static constexpr
Definition at line 28 of file ExtrapTrackData.hpp.
Referenced by TEST_F().
MULTICAST_ADDRESS
constexpr const char* domain::model::ExtrapTrackData::MULTICAST_ADDRESS = "239.1.1.5" static constexpr
Definition at line 23 of file ExtrapTrackData.hpp.
Referenced by TEST_F().
originalUpdateTime_
int64_t domain::model::ExtrapTrackData::originalUpdateTime_ private
Original güncelleme zamanı (mikrosaniye)
Definition at line 104 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getOriginalUpdateTime(), getSerializedSize(), isValid(), serialize(), and setOriginalUpdateTime().
PORT
constexpr int domain::model::ExtrapTrackData::PORT = 9596 static constexpr
Definition at line 24 of file ExtrapTrackData.hpp.
Referenced by TEST_F().
trackId_
int32_t domain::model::ExtrapTrackData::trackId_ private
İz için benzersiz tam sayı kimliği.
Definition at line 90 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getTrackId(), isValid(), serialize(), and setTrackId().
updateTime_
int64_t domain::model::ExtrapTrackData::updateTime_ private
Son güncelleme zamanı (mikrosaniye)
Definition at line 106 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getUpdateTime(), isValid(), serialize(), and setUpdateTime().
xPositionECEF_
double domain::model::ExtrapTrackData::xPositionECEF_ private
ECEF koordinatlarındaki X ekseni konumu (metre)
Definition at line 98 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getXPositionECEF(), isValid(), serialize(), and setXPositionECEF().
xVelocityECEF_
double domain::model::ExtrapTrackData::xVelocityECEF_ private
ECEF koordinatlarındaki X ekseni hızı (m/s)
Definition at line 92 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getXVelocityECEF(), isValid(), serialize(), and setXVelocityECEF().
yPositionECEF_
double domain::model::ExtrapTrackData::yPositionECEF_ private
ECEF koordinatlarındaki Y ekseni konumu (metre)
Definition at line 100 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getYPositionECEF(), isValid(), serialize(), and setYPositionECEF().
yVelocityECEF_
double domain::model::ExtrapTrackData::yVelocityECEF_ private
ECEF koordinatlarındaki Y ekseni hızı (m/s)
Definition at line 94 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getYVelocityECEF(), isValid(), serialize(), and setYVelocityECEF().
ZMQ_SOCKET_TYPE
constexpr const char* domain::model::ExtrapTrackData::ZMQ_SOCKET_TYPE = "RADIO" static constexpr
Definition at line 27 of file ExtrapTrackData.hpp.
Referenced by TEST_F().
zPositionECEF_
double domain::model::ExtrapTrackData::zPositionECEF_ private
ECEF koordinatlarındaki Z ekseni konumu (metre)
Definition at line 102 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getZPositionECEF(), isValid(), serialize(), and setZPositionECEF().
zVelocityECEF_
double domain::model::ExtrapTrackData::zVelocityECEF_ private
ECEF koordinatlarındaki Z ekseni hızı (m/s)
Definition at line 96 of file ExtrapTrackData.hpp.
Referenced by ExtrapTrackData(), getSerializedSize(), getZVelocityECEF(), isValid(), serialize(), and setZVelocityECEF().
The documentation for this class was generated from the following files:
a_hexagon/domain/ports/ExtrapTrackData.hpp
a_hexagon/domain/model/ExtrapTrackData.cpp