a_hexagon: a_hexagon/main.cpp File Reference
main.cpp File Reference
Main entry point for A_Hexagon application.
#include <iostream>
#include <csignal>
#include <atomic>
#include <thread>
#include <chrono>
#include <memory>
#include "utils/Logger.hpp"
#include "adapters/common/AdapterManager.hpp"
#include "adapters/common/MessagePipeline.hpp"
#include "adapters/common/messaging/IMessageSocket.hpp"
#include "adapters/common/messaging/ZeroMQSocket.hpp"
#include "adapters/incoming/zeromq/TrackDataZeroMQIncomingAdapter.hpp"
#include "adapters/outgoing/zeromq/ExtrapTrackDataZeroMQOutgoingAdapter.hpp"
#include "domain/logic/TrackDataExtrapolator.hpp"
Namespaces
namespace config
Functions
void signalHandler (int signum)
Signal handler for graceful shutdown.
std::unique_ptr< adapters::common::messaging::IMessageSocket > createIncomingSocket ()
Create socket for incoming TrackData (DIP compliant)
std::unique_ptr< adapters::common::messaging::IMessageSocket > createOutgoingSocket ()
Create socket for outgoing ExtrapTrackData (DIP compliant)
int main ()
Variables
static std::atomic< bool > g_running {true}
static constexpr const char * config::TRACK_DATA_INCOMING_ENDPOINT = "udp://239.1.1.1:9000"
static constexpr const char * config::TRACK_DATA_INCOMING_GROUP = "TrackData"
static constexpr const char * config::EXTRAP_DATA_OUTGOING_ENDPOINT = "udp://239.1.1.2:9001"
static constexpr const char * config::EXTRAP_DATA_OUTGOING_GROUP = "ExtrapTrackData"
Detailed Description
Main entry point for A_Hexagon application.
Initializes the async logger and starts the hexagonal architecture components using Thread-per-Type architecture for adapter isolation
Architecture Overview: ┌─────────────────────────────────────────────────────────────────────┐ │ THREAD-PER-TYPE ARCHITECTURE │ ├─────────────────────────────────────────────────────────────────────┤ │ │ │ ┌─────────────────────────────────────────────────────────────┐ │ │ │ TrackData Pipeline │ │ │ ├─────────────────────────────────────────────────────────────┤ │ │ │ TrackDataZeroMQIncomingAdapter (Thread T1) │ │ │ │ ↓ │ │ │ │ TrackDataExtrapolator (Domain Service) │ │ │ │ ↓ │ │ │ │ ExtrapTrackDataZeroMQOutgoingAdapter │ │ │ └─────────────────────────────────────────────────────────────┘ │ │ │ │ Each pipeline operates in COMPLETE ISOLATION - zero contention! │ │ │ │ DIP Compliant: Adapters depend on IMessageSocket abstraction │ │ Production uses ZeroMQSocket, Tests use MockMessageSocket │ └─────────────────────────────────────────────────────────────────────┘
Author
a_hexagon Team
Version
2.1
Date
2025
Note
MISRA C++ 2023 compliant implementation
DIP compliant - socket injection for testability
Definition in file main.cpp.
Function Documentation
createIncomingSocket()
std::unique_ptr< adapters::common::messaging::IMessageSocket > createIncomingSocket ()
Create socket for incoming TrackData (DIP compliant)
Returns
Configured socket ready for binding (UDP DISH)
Definition at line 89 of file main.cpp.
References adapters::common::messaging::ZeroMQSocket::Bind, adapters::common::messaging::ZeroMQSocket::DISH, LOG_ERROR, LOG_INFO, config::TRACK_DATA_INCOMING_ENDPOINT, and config::TRACK_DATA_INCOMING_GROUP.
Referenced by main().
createOutgoingSocket()
std::unique_ptr< adapters::common::messaging::IMessageSocket > createOutgoingSocket ()
Create socket for outgoing ExtrapTrackData (DIP compliant)
Returns
Configured socket ready for connecting (UDP RADIO)
Definition at line 113 of file main.cpp.
References adapters::common::messaging::ZeroMQSocket::Connect, config::EXTRAP_DATA_OUTGOING_ENDPOINT, config::EXTRAP_DATA_OUTGOING_GROUP, LOG_ERROR, LOG_INFO, and adapters::common::messaging::ZeroMQSocket::RADIO.
Referenced by main().
main()
int main ()
Definition at line 130 of file main.cpp.
References createIncomingSocket(), createOutgoingSocket(), g_running, adapters::AdapterManager::getPipelineCount(), utils::Logger::init(), LOG_CRITICAL, LOG_ERROR, LOG_INFO, adapters::AdapterManager::registerPipeline(), utils::Logger::shutdown(), signalHandler(), adapters::AdapterManager::startAll(), and adapters::AdapterManager::stopAll().
signalHandler()
void signalHandler (int signum)
Signal handler for graceful shutdown.
Parameters
signum Signal number received (SIGINT, SIGTERM)
Postcondition
g_shutdown_requested is set to true
Note
Registered via std::signal() in main()
Definition at line 66 of file main.cpp.
References g_running, and LOG_INFO.
Referenced by main().
Variable Documentation
g_running
std::atomic<bool> g_running {true} static
Definition at line 63 of file main.cpp.
Referenced by main(), and signalHandler().