a_hexagon: adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter Class Reference
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter Class Reference
Receives TrackData via IMessageSocket abstraction.
#include <TrackDataZeroMQIncomingAdapter.hpp>
Public Member Functions
TrackDataZeroMQIncomingAdapter (std::shared_ptr< domain::ports::incoming::ITrackDataIncomingPort > incomingPort, std::unique_ptr< adapters::common::messaging::IMessageSocket > socket)
Construct adapter with DIP - socket injection (preferred for testing)
TrackDataZeroMQIncomingAdapter (domain::ports::incoming::ITrackDataIncomingPort *incomingPort)
Construct adapter with domain port (raw pointer - legacy)
TrackDataZeroMQIncomingAdapter (std::shared_ptr< domain::ports::incoming::ITrackDataIncomingPort > incomingPort)
Construct adapter with domain port (shared_ptr - legacy)
~TrackDataZeroMQIncomingAdapter () override
Destructor - ensures graceful shutdown.
bool start () override
Start the adapter's receive loop.
void stop () override
Stop the adapter gracefully.
bool isRunning () const override
Check if adapter is running.
std::string getName () const noexcept override
Get adapter name.
TrackDataZeroMQIncomingAdapter (const TrackDataZeroMQIncomingAdapter &)=delete
TrackDataZeroMQIncomingAdapter & operator= (const TrackDataZeroMQIncomingAdapter &)=delete
TrackDataZeroMQIncomingAdapter (TrackDataZeroMQIncomingAdapter &&)=delete
TrackDataZeroMQIncomingAdapter & operator= (TrackDataZeroMQIncomingAdapter &&)=delete
Public Member Functions inherited from adapters::IAdapter
virtual ~IAdapter ()=default
Virtual destructor for proper cleanup.
Private Member Functions
void loadConfiguration ()
Load configuration (for legacy constructors)
bool initializeSocket ()
Initialize socket (for legacy constructors)
void receiveLoop ()
Main receive loop (runs in dedicated thread)
bool deserializeTrackData (const std::vector< uint8_t > &data, domain::model::TrackData &trackData)
Deserialize binary data to TrackData.
Private Attributes
std::string endpoint_
ZeroMQ endpoint.
int32_t receiveTimeout_
Receive timeout in ms.
std::unique_ptr< adapters::common::messaging::IMessageSocket > socket_
Socket abstraction.
std::thread receiveThread_
Dedicated receive thread.
std::atomic< bool > running_
Running state flag.
std::atomic< bool > stopRequested_
Stop signal flag.
domain::ports::incoming::ITrackDataIncomingPort * incomingPort_
Domain service port (raw)
std::shared_ptr< domain::ports::incoming::ITrackDataIncomingPort > incomingPortShared_
Domain service port (shared)
bool ownsSocket_ {false}
Static Private Attributes
static constexpr const char * DEFAULT_ENDPOINT {"udp://239.1.1.1:9000"}
static constexpr const char * DEFAULT_GROUP {"TrackData"}
static constexpr int32_t DEFAULT_RECEIVE_TIMEOUT {100}
Receive timeout (ms)
static constexpr int32_t REALTIME_THREAD_PRIORITY {95}
SCHED_FIFO priority.
static constexpr int32_t DEDICATED_CPU_CORE {1}
CPU affinity core.
Additional Inherited Members
Protected Member Functions inherited from adapters::IAdapter
IAdapter ()=default
Protected default constructor.
IAdapter (const IAdapter &)=default
Protected copy constructor.
IAdapter (IAdapter &&)=default
Protected move constructor.
IAdapter & operator= (const IAdapter &)=default
Protected copy assignment.
IAdapter & operator= (IAdapter &&)=default
Protected move assignment.
Detailed Description
Receives TrackData via IMessageSocket abstraction.
Implements IAdapter interface for lifecycle management. Each instance runs in its own dedicated thread with real-time priority and CPU affinity support. DIP compliant - socket is injected for testability.
Class Invariants:
When running_, receiveThread_ is active
Class Invariants:
socket_ is properly configured before start()
Definition at line 58 of file TrackDataZeroMQIncomingAdapter.hpp.
Constructor & Destructor Documentation
TrackDataZeroMQIncomingAdapter() [1/5]
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::TrackDataZeroMQIncomingAdapter (std::shared_ptr< domain::ports::incoming::ITrackDataIncomingPort > incomingPort, std::unique_ptr< adapters::common::messaging::IMessageSocket > socket) explicit
Construct adapter with DIP - socket injection (preferred for testing)
Parameters
incomingPort Domain service port for processing received data
socket Message socket abstraction (ZeroMQ or Mock)
Precondition
incomingPort is not null
socket is not null
Postcondition
Adapter is configured but not started
Definition at line 36 of file TrackDataZeroMQIncomingAdapter.cpp.
References LOG_INFO.
TrackDataZeroMQIncomingAdapter() [2/5]
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::TrackDataZeroMQIncomingAdapter (domain::ports::incoming::ITrackDataIncomingPort * incomingPort) explicit
Construct adapter with domain port (raw pointer - legacy)
Parameters
incomingPort Domain service port for processing received data
Precondition
incomingPort is not null
Postcondition
Adapter is configured but not started
Deprecated:
Use socket injection constructor for new code
Definition at line 53 of file TrackDataZeroMQIncomingAdapter.cpp.
References endpoint_, loadConfiguration(), and LOG_INFO.
TrackDataZeroMQIncomingAdapter() [3/5]
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::TrackDataZeroMQIncomingAdapter (std::shared_ptr< domain::ports::incoming::ITrackDataIncomingPort > incomingPort) explicit
Construct adapter with domain port (shared_ptr - legacy)
Parameters
incomingPort Domain service port for processing received data
Precondition
incomingPort is not null
Postcondition
Adapter is configured but not started
Deprecated:
Use socket injection constructor for new code
Definition at line 68 of file TrackDataZeroMQIncomingAdapter.cpp.
References endpoint_, loadConfiguration(), and LOG_INFO.
~TrackDataZeroMQIncomingAdapter()
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::~TrackDataZeroMQIncomingAdapter () override
Destructor - ensures graceful shutdown.
Postcondition
Receive thread is stopped
ZeroMQ socket is closed
Definition at line 83 of file TrackDataZeroMQIncomingAdapter.cpp.
References LOG_DEBUG, and stop().
TrackDataZeroMQIncomingAdapter() [4/5]
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::TrackDataZeroMQIncomingAdapter (const TrackDataZeroMQIncomingAdapter &) delete
TrackDataZeroMQIncomingAdapter() [5/5]
adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::TrackDataZeroMQIncomingAdapter (TrackDataZeroMQIncomingAdapter &&) delete
Member Function Documentation
deserializeTrackData()
bool adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::deserializeTrackData (const std::vector< uint8_t > & data, domain::model::TrackData & trackData) private
Deserialize binary data to TrackData.
Parameters
data Raw binary message data
trackData Output TrackData object
Returns
true if deserialization successful
Definition at line 288 of file TrackDataZeroMQIncomingAdapter.cpp.
References LOG_DEBUG, LOG_ERROR, domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
getName()
std::string adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::getName () const override virtual noexcept
Get adapter name.
Returns
"TrackDataZeroMQIncomingAdapter"
Implements adapters::IAdapter.
Definition at line 231 of file TrackDataZeroMQIncomingAdapter.cpp.
initializeSocket()
bool adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::initializeSocket () private
Initialize socket (for legacy constructors)
Returns
true if socket initialized successfully
Definition at line 96 of file TrackDataZeroMQIncomingAdapter.cpp.
References adapters::common::messaging::ZeroMQSocket::Bind, DEFAULT_GROUP, endpoint_, adapters::common::messaging::ZeroMQSocket::joinGroup(), LOG_ERROR, LOG_INFO, ownsSocket_, socket_, and ZMQ_DISH.
Referenced by start().
isRunning()
bool adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::isRunning () const override virtual
Check if adapter is running.
Returns
true if receive loop is active
Implements adapters::IAdapter.
Definition at line 227 of file TrackDataZeroMQIncomingAdapter.cpp.
References running_.
loadConfiguration()
void adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::loadConfiguration () private
Load configuration (for legacy constructors)
Reads from config file or uses defaults
Definition at line 88 of file TrackDataZeroMQIncomingAdapter.cpp.
References DEFAULT_ENDPOINT, DEFAULT_RECEIVE_TIMEOUT, endpoint_, LOG_DEBUG, and receiveTimeout_.
Referenced by TrackDataZeroMQIncomingAdapter(), and TrackDataZeroMQIncomingAdapter().
operator=() [1/2]
TrackDataZeroMQIncomingAdapter & adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::operator= (const TrackDataZeroMQIncomingAdapter &) delete
operator=() [2/2]
TrackDataZeroMQIncomingAdapter & adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::operator= (TrackDataZeroMQIncomingAdapter &&) delete
receiveLoop()
void adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop () private
Main receive loop (runs in dedicated thread)
Continuously receives and processes messages until stopped
Definition at line 235 of file TrackDataZeroMQIncomingAdapter.cpp.
References domain::model::TrackData::deserialize(), domain::model::TrackData::getOriginalUpdateTime(), domain::model::TrackData::getTrackId(), incomingPort_, domain::model::TrackData::isValid(), LOG_DEBUG, LOG_ERROR, LOG_INFO, LOG_TRACE, LOG_WARN, utils::Logger::logTrackReceived(), domain::ports::incoming::ITrackDataIncomingPort::processAndForwardTrackData(), receiveTimeout_, socket_, and stopRequested_.
Referenced by start().
start()
bool adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::start () override virtual
Start the adapter's receive loop.
Returns
true if started successfully
Postcondition
isRunning() returns true
Receive thread is active
Implements adapters::IAdapter.
Definition at line 134 of file TrackDataZeroMQIncomingAdapter.cpp.
References DEDICATED_CPU_CORE, endpoint_, incomingPort_, initializeSocket(), LOG_ERROR, LOG_INFO, LOG_WARN, ownsSocket_, REALTIME_THREAD_PRIORITY, receiveLoop(), receiveThread_, running_, socket_, and stopRequested_.
stop()
void adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::stop () override virtual
Stop the adapter gracefully.
Signals receive loop to exit and joins thread
Postcondition
isRunning() returns false
Receive thread has terminated
Implements adapters::IAdapter.
Definition at line 201 of file TrackDataZeroMQIncomingAdapter.cpp.
References LOG_INFO, ownsSocket_, receiveThread_, running_, socket_, and stopRequested_.
Referenced by ~TrackDataZeroMQIncomingAdapter().
Member Data Documentation
DEDICATED_CPU_CORE
constexpr int32_t adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::DEDICATED_CPU_CORE {1} static constexpr private
CPU affinity core.
Definition at line 190 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by start().
DEFAULT_ENDPOINT
constexpr const char* adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::DEFAULT_ENDPOINT {"udp://239.1.1.1:9000"} static constexpr private
Definition at line 184 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by loadConfiguration().
DEFAULT_GROUP
constexpr const char* adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::DEFAULT_GROUP {"TrackData"} static constexpr private
Definition at line 185 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by initializeSocket().
DEFAULT_RECEIVE_TIMEOUT
constexpr int32_t adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::DEFAULT_RECEIVE_TIMEOUT {100} static constexpr private
Receive timeout (ms)
Definition at line 186 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by loadConfiguration().
endpoint_
std::string adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::endpoint_ private
ZeroMQ endpoint.
Definition at line 164 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by TrackDataZeroMQIncomingAdapter(), TrackDataZeroMQIncomingAdapter(), initializeSocket(), loadConfiguration(), and start().
incomingPort_
domain::ports::incoming::ITrackDataIncomingPort* adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::incomingPort_ private
Domain service port (raw)
Definition at line 176 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by receiveLoop(), and start().
incomingPortShared_
std::shared_ptr<domain::ports::incoming::ITrackDataIncomingPort> adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::incomingPortShared_ private
Domain service port (shared)
Definition at line 177 of file TrackDataZeroMQIncomingAdapter.hpp.
ownsSocket_
bool adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::ownsSocket_ {false} private
Definition at line 180 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by initializeSocket(), start(), and stop().
REALTIME_THREAD_PRIORITY
constexpr int32_t adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::REALTIME_THREAD_PRIORITY {95} static constexpr private
SCHED_FIFO priority.
Definition at line 189 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by start().
receiveThread_
std::thread adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveThread_ private
Dedicated receive thread.
Definition at line 171 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by start(), and stop().
receiveTimeout_
int32_t adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveTimeout_ private
Receive timeout in ms.
Definition at line 165 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by loadConfiguration(), and receiveLoop().
running_
std::atomic<bool> adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::running_ private
Running state flag.
Definition at line 172 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by isRunning(), start(), and stop().
socket_
std::unique_ptr<adapters::common::messaging::IMessageSocket> adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::socket_ private
Socket abstraction.
Definition at line 168 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by initializeSocket(), receiveLoop(), start(), and stop().
stopRequested_
std::atomic<bool> adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::stopRequested_ private
Stop signal flag.
Definition at line 173 of file TrackDataZeroMQIncomingAdapter.hpp.
Referenced by receiveLoop(), start(), and stop().
The documentation for this class was generated from the following files:
a_hexagon/adapters/incoming/zeromq/TrackDataZeroMQIncomingAdapter.hpp
a_hexagon/adapters/incoming/zeromq/TrackDataZeroMQIncomingAdapter.cpp