a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/adapters/incoming/TrackDataZeroMQIncomingAdapterTest.cpp File Reference
TrackDataZeroMQIncomingAdapterTest.cpp File Reference
Unit tests for TrackDataZeroMQIncomingAdapter with DIP compliance.
#include <gtest/gtest.h>
#include <memory>
#include <chrono>
#include <thread>
#include "adapters/incoming/zeromq/TrackDataZeroMQIncomingAdapter.hpp"
#include "../../mocks/MockMessageSocket.hpp"
#include "../../mocks/MockIncomingPort.hpp"
#include "domain/ports/TrackData.hpp"
Classes
class TrackDataZeroMQIncomingAdapterTest
Test fixture for TrackDataZeroMQIncomingAdapter.
Functions
TEST_F (TrackDataZeroMQIncomingAdapterTest, Constructor_WithValidDependencies_CreatesAdapter)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Start_WithConnectedSocket_StartsSuccessfully)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Start_WhenAlreadyRunning_ReturnsTrue)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Stop_WhenRunning_StopsAdapter)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Stop_WhenNotRunning_DoesNothing)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Destructor_WhenRunning_StopsGracefully)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_WithValidMessage_ForwardsToPort)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_WithMultipleMessages_ForwardsAllToPort)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_WithInvalidMessage_SkipsAndContinues)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_WithEmptyMessage_HandlesGracefully)
TEST_F (TrackDataZeroMQIncomingAdapterTest, Start_WithFailedConnect_HandlesError)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_WhenSocketDisconnects_StopsGracefully)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_PreservesTrackId)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_PreservesPosition)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_PreservesVelocity)
TEST_F (TrackDataZeroMQIncomingAdapterTest, HighThroughput_ProcessesMessagesQuickly)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ConcurrentStartStop_IsThreadSafe)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_VerifySocketReceiveCalls)
TEST_F (TrackDataZeroMQIncomingAdapterTest, ReceiveLoop_VerifyPortProcessCalls)
Detailed Description
Unit tests for TrackDataZeroMQIncomingAdapter with DIP compliance.
Tests adapter behavior using MockMessageSocket (no real network) Achieves %95+ code coverage through dependency injection
Author
a_hexagon Team
Version
2.0
Date
2025
Note
MISRA C++ 2023 compliant test implementation
Definition in file TrackDataZeroMQIncomingAdapterTest.cpp.
Function Documentation
TEST_F() [1/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ConcurrentStartStop_IsThreadSafe)
Definition at line 359 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [2/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Constructor_WithValidDependencies_CreatesAdapter)
Definition at line 86 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [3/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Destructor_WhenRunning_StopsGracefully)
Definition at line 131 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [4/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , HighThroughput_ProcessesMessagesQuickly)
Definition at line 331 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [5/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_PreservesPosition)
Definition at line 279 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References domain::model::TrackData::serialize(), domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [6/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_PreservesTrackId)
Definition at line 264 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [7/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_PreservesVelocity)
Definition at line 304 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References domain::model::TrackData::serialize(), domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [8/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_VerifyPortProcessCalls)
Definition at line 389 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [9/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_VerifySocketReceiveCalls)
Definition at line 376 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [10/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_WhenSocketDisconnects_StopsGracefully)
Definition at line 247 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [11/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_WithEmptyMessage_HandlesGracefully)
Definition at line 214 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [12/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_WithInvalidMessage_SkipsAndContinues)
Definition at line 192 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [13/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_WithMultipleMessages_ForwardsAllToPort)
Definition at line 166 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [14/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , ReceiveLoop_WithValidMessage_ForwardsToPort)
Definition at line 143 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [15/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Start_WhenAlreadyRunning_ReturnsTrue)
Definition at line 103 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [16/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Start_WithConnectedSocket_StartsSuccessfully)
Definition at line 94 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [17/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Start_WithFailedConnect_HandlesError)
Definition at line 232 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [18/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Stop_WhenNotRunning_DoesNothing)
Definition at line 123 of file TrackDataZeroMQIncomingAdapterTest.cpp.
TEST_F() [19/19]
TEST_F (TrackDataZeroMQIncomingAdapterTest , Stop_WhenRunning_StopsAdapter)
Definition at line 113 of file TrackDataZeroMQIncomingAdapterTest.cpp.