a_hexagon: /workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/domain/logic/TrackDataExtrapolatorTest.cpp File Reference
TrackDataExtrapolatorTest.cpp File Reference
Unit tests for TrackDataExtrapolator domain logic.
#include <gtest/gtest.h>
#include <memory>
#include <cmath>
#include <chrono>
#include "domain/logic/TrackDataExtrapolator.hpp"
#include "../../mocks/MockOutgoingPort.hpp"
#include "domain/ports/TrackData.hpp"
#include "domain/ports/ExtrapTrackData.hpp"
Classes
class TrackDataExtrapolatorTest
Test fixture for TrackDataExtrapolator.
Functions
TEST_F (TrackDataExtrapolatorTest, Constructor_WithValidPort_CreatesExtrapolator)
TEST_F (TrackDataExtrapolatorTest, Constructor_WithNullPort_DoesNotCrash)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_GeneratesMultipleOutputs)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_PreservesTrackId)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_PreservesVelocity)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_PreservesOriginalUpdateTime)
TEST_F (TrackDataExtrapolatorTest, ExtrapolateTrackData_CalculatesPositionCorrectly)
TEST_F (TrackDataExtrapolatorTest, ExtrapolateTrackData_IncrementsUpdateTime)
TEST_F (TrackDataExtrapolatorTest, ExtrapolateTrackData_SetsFirstHopSentTime)
TEST_F (TrackDataExtrapolatorTest, FrequencyInterval_8HzInput_125msInterval)
TEST_F (TrackDataExtrapolatorTest, FrequencyInterval_100HzOutput_10msInterval)
TEST_F (TrackDataExtrapolatorTest, ExtrapolationCount_8HzTo100Hz_Approximately12Outputs)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_WithZeroVelocity_PositionUnchanged)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_WithNegativeVelocity_DecrementsPosition)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_WithLargeVelocity_HandlesCorrectly)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_CallsSendForEachOutput)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_MultipleInputs_ProcessesAll)
TEST_F (TrackDataExtrapolatorTest, ProcessAndForwardTrackData_WhenPortFails_HandlesGracefully)
Detailed Description
Unit tests for TrackDataExtrapolator domain logic.
Tests extrapolation logic using MockOutgoingPort (no network) Achieves %95+ code coverage through dependency injection
Author
a_hexagon Team
Version
2.0
Date
2025
Note
MISRA C++ 2023 compliant test implementation
Definition in file TrackDataExtrapolatorTest.cpp.
Function Documentation
TEST_F() [1/18]
TEST_F (TrackDataExtrapolatorTest , Constructor_WithNullPort_DoesNotCrash)
Definition at line 78 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [2/18]
TEST_F (TrackDataExtrapolatorTest , Constructor_WithValidPort_CreatesExtrapolator)
Definition at line 72 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [3/18]
TEST_F (TrackDataExtrapolatorTest , ExtrapolateTrackData_CalculatesPositionCorrectly)
Definition at line 171 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [4/18]
TEST_F (TrackDataExtrapolatorTest , ExtrapolateTrackData_IncrementsUpdateTime)
Definition at line 210 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [5/18]
TEST_F (TrackDataExtrapolatorTest , ExtrapolateTrackData_SetsFirstHopSentTime)
Definition at line 237 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [6/18]
TEST_F (TrackDataExtrapolatorTest , ExtrapolationCount_8HzTo100Hz_Approximately12Outputs)
Definition at line 276 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [7/18]
TEST_F (TrackDataExtrapolatorTest , FrequencyInterval_100HzOutput_10msInterval)
Definition at line 269 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [8/18]
TEST_F (TrackDataExtrapolatorTest , FrequencyInterval_8HzInput_125msInterval)
Definition at line 262 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [9/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_CallsSendForEachOutput)
Definition at line 373 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [10/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_GeneratesMultipleOutputs)
Definition at line 87 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [11/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_MultipleInputs_ProcessesAll)
Definition at line 389 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [12/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_PreservesOriginalUpdateTime)
Definition at line 145 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [13/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_PreservesTrackId)
Definition at line 104 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [14/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_PreservesVelocity)
Definition at line 120 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [15/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_WhenPortFails_HandlesGracefully)
Definition at line 406 of file TrackDataExtrapolatorTest.cpp.
TEST_F() [16/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_WithLargeVelocity_HandlesCorrectly)
Definition at line 345 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [17/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_WithNegativeVelocity_DecrementsPosition)
Definition at line 318 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
TEST_F() [18/18]
TEST_F (TrackDataExtrapolatorTest , ProcessAndForwardTrackData_WithZeroVelocity_PositionUnchanged)
Definition at line 292 of file TrackDataExtrapolatorTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().