a_hexagon: TrackDataZeroMQIncomingAdapterTest Class Reference
TrackDataZeroMQIncomingAdapterTest Class Reference
Test fixture for TrackDataZeroMQIncomingAdapter.
Protected Member Functions
void SetUp () override
void TearDown () override
void createAdapter ()
Create adapter with mock dependencies (DIP injection)
TrackData createTestTrackData (int32_t trackId)
Create valid test TrackData.
Protected Attributes
std::unique_ptr< MockMessageSocket > mockSocket_
MockMessageSocket * mockSocketPtr_ {nullptr}
std::shared_ptr< MockIncomingPort > mockPort_
std::unique_ptr< TrackDataZeroMQIncomingAdapter > adapter_
Detailed Description
Test fixture for TrackDataZeroMQIncomingAdapter.
Definition at line 31 of file TrackDataZeroMQIncomingAdapterTest.cpp.
Member Function Documentation
createAdapter()
void TrackDataZeroMQIncomingAdapterTest::createAdapter () inline protected
Create adapter with mock dependencies (DIP injection)
Definition at line 53 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References adapter_, mockPort_, and mockSocket_.
createTestTrackData()
TrackData TrackDataZeroMQIncomingAdapterTest::createTestTrackData (int32_t trackId) inline protected
Create valid test TrackData.
Definition at line 63 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), and domain::model::TrackData::setZVelocityECEF().
SetUp()
void TrackDataZeroMQIncomingAdapterTest::SetUp () inline override protected
Definition at line 33 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References mockPort_, mockSocket_, and mockSocketPtr_.
TearDown()
void TrackDataZeroMQIncomingAdapterTest::TearDown () inline override protected
Definition at line 44 of file TrackDataZeroMQIncomingAdapterTest.cpp.
References adapter_.
Member Data Documentation
adapter_
std::unique_ptr<TrackDataZeroMQIncomingAdapter> TrackDataZeroMQIncomingAdapterTest::adapter_ protected
Definition at line 81 of file TrackDataZeroMQIncomingAdapterTest.cpp.
Referenced by createAdapter(), and TearDown().
mockPort_
std::shared_ptr<MockIncomingPort> TrackDataZeroMQIncomingAdapterTest::mockPort_ protected
Definition at line 80 of file TrackDataZeroMQIncomingAdapterTest.cpp.
Referenced by createAdapter(), and SetUp().
mockSocket_
std::unique_ptr<MockMessageSocket> TrackDataZeroMQIncomingAdapterTest::mockSocket_ protected
Definition at line 78 of file TrackDataZeroMQIncomingAdapterTest.cpp.
Referenced by createAdapter(), and SetUp().
mockSocketPtr_
MockMessageSocket* TrackDataZeroMQIncomingAdapterTest::mockSocketPtr_ {nullptr} protected
Definition at line 79 of file TrackDataZeroMQIncomingAdapterTest.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
/workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/adapters/incoming/TrackDataZeroMQIncomingAdapterTest.cpp