a_hexagon: utils::Logger Class Reference
utils::Logger Class Reference
Thread-safe async logger wrapper using spdlog.
#include <Logger.hpp>
Public Types
enum class Level {
Trace = 0 , Debug = 1 , Info = 2 , Warn = 3 ,
Error = 4 , Critical = 5 , Off = 6
}
Log levels matching spdlog levels.
Static Public Member Functions
static void init (const std::string &app_name="a_hexagon", std::size_t queue_size=8192, std::size_t thread_count=1)
Initialize the async logger with default configuration.
static void initWithFile (const std::string &app_name, const std::string &log_file, std::size_t max_file_size=5 *1024 *1024, std::size_t max_files=3)
Initialize logger with file output.
static void setLevel (Level level)
Set the minimum log level.
static void shutdown ()
Shutdown logger and flush all pending messages.
template<typename... Args>
static void trace (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
static void debug (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
static void info (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
static void warn (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
static void error (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
static void critical (spdlog::format_string_t< Args... > fmt, Args &&... args)
static void logLatency (const std::string &component, const std::string &operation, int64_t latency_us)
Log latency measurement (commonly used in real-time systems)
static void logTrackReceived (int32_t track_id, int64_t hop_latency)
Log track data reception.
static void logTrackExtrapolated (int32_t track_id, int extrap_count, int64_t latency_us)
Log track data extrapolation.
static bool isInitialized () noexcept
Private Member Functions
Logger ()=default
~Logger ()=default
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Static Private Attributes
static bool initialized_ {false}
Detailed Description
Thread-safe async logger wrapper using spdlog.
Static class with lazy initialization Configurable async queue size and thread pool
Definition at line 49 of file Logger.hpp.
Member Enumeration Documentation
Level
enum class utils::Logger::Level strong
Log levels matching spdlog levels.
Enumerator
Trace
Debug
Info
Warn
Error
Critical
Off
Definition at line 54 of file Logger.hpp.
Constructor & Destructor Documentation
Logger() [1/2]
utils::Logger::Logger () private default
~Logger()
utils::Logger::~Logger () private default
Logger() [2/2]
utils::Logger::Logger (const Logger &) private delete
Member Function Documentation
critical()
template<typename... Args> static void utils::Logger::critical (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 187 of file Logger.hpp.
Referenced by Logger::critical(), and TEST_F().
debug()
template<typename... Args> static void utils::Logger::debug (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 167 of file Logger.hpp.
Referenced by Logger::debug(), TEST_F(), and TEST_F().
error()
template<typename... Args> static void utils::Logger::error (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 182 of file Logger.hpp.
Referenced by Logger::error(), and TEST_F().
info()
template<typename... Args> static void utils::Logger::info (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 172 of file Logger.hpp.
Referenced by Logger::info(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
init()
static void utils::Logger::init (const std::string & app_name = "a_hexagon", std::size_t queue_size = 8192, std::size_t thread_count = 1) inline static
Initialize the async logger with default configuration.
Parameters
app_name Application name for log identification
queue_size Async queue size (default 8192 for low latency)
thread_count Background thread count (default 1)
Note
Call once at application startup before any logging
Definition at line 71 of file Logger.hpp.
References initialized_.
Referenced by Logger::initialize(), main(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
initWithFile()
static void utils::Logger::initWithFile (const std::string & app_name, const std::string & log_file, std::size_t max_file_size = 5 * 1024 * 1024, std::size_t max_files = 3) inline static
Initialize logger with file output.
Parameters
app_name Application name
log_file Path to log file
max_file_size Max file size before rotation (default 5MB)
max_files Max number of rotated files (default 3)
Definition at line 108 of file Logger.hpp.
References initialized_.
Referenced by Logger::initialize(), and TEST_F().
isInitialized()
static bool utils::Logger::isInitialized () inline static noexcept
Definition at line 225 of file Logger.hpp.
References initialized_.
Referenced by Logger::isInitialized(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
logLatency()
static void utils::Logger::logLatency (const std::string & component, const std::string & operation, int64_t latency_us) inline static
Log latency measurement (commonly used in real-time systems)
Parameters
component Component name (e.g., "ZMQ", "Domain")
operation Operation name (e.g., "receive", "process")
latency_us Latency in microseconds
Definition at line 199 of file Logger.hpp.
Referenced by TEST_F(), TEST_F(), and TEST_F().
logTrackExtrapolated()
static void utils::Logger::logTrackExtrapolated (int32_t track_id, int extrap_count, int64_t latency_us) inline static
Log track data extrapolation.
Parameters
track_id Track identifier
extrap_count Number of extrapolated samples
latency_us Processing latency in microseconds
Definition at line 220 of file Logger.hpp.
logTrackReceived()
static void utils::Logger::logTrackReceived (int32_t track_id, int64_t hop_latency) inline static
Log track data reception.
Parameters
track_id Track identifier
hop_latency Latency in microseconds
Definition at line 210 of file Logger.hpp.
Referenced by adapters::incoming::zeromq::TrackDataZeroMQIncomingAdapter::receiveLoop(), TEST_F(), and TEST_F().
operator=()
Logger & utils::Logger::operator= (const Logger &) private delete
setLevel()
static void utils::Logger::setLevel (Level level) inline static
Set the minimum log level.
Parameters
level Minimum level to display
Definition at line 146 of file Logger.hpp.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
shutdown()
static void utils::Logger::shutdown () inline static
Shutdown logger and flush all pending messages.
Note
Call at application shutdown
Definition at line 154 of file Logger.hpp.
References initialized_.
Referenced by main(), LoggerTest::SetUp(), Logger::shutdown(), LoggerTest::TearDown(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
trace()
template<typename... Args> static void utils::Logger::trace (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 162 of file Logger.hpp.
Referenced by TEST_F(), and Logger::trace().
warn()
template<typename... Args> static void utils::Logger::warn (spdlog::format_string_t< Args... > fmt, Args &&... args) inline static
Definition at line 177 of file Logger.hpp.
Referenced by TEST_F(), and Logger::warn().
Member Data Documentation
initialized_
bool utils::Logger::initialized_ {false} inline static private
Definition at line 235 of file Logger.hpp.
Referenced by init(), initWithFile(), isInitialized(), and shutdown().
The documentation for this class was generated from the following file:
a_hexagon/utils/Logger.hpp