a_hexagon: TrackDataTest Class Reference
TrackDataTest Class Reference
Test fixture for TrackData tests.
Protected Member Functions
void SetUp () override
Protected Attributes
TrackData validTrackData_
Detailed Description
Test fixture for TrackData tests.
Definition at line 22 of file TrackDataTest.cpp.
Member Function Documentation
SetUp()
void TrackDataTest::SetUp () inline override protected
Definition at line 24 of file TrackDataTest.cpp.
References domain::model::TrackData::setOriginalUpdateTime(), domain::model::TrackData::setTrackId(), domain::model::TrackData::setXPositionECEF(), domain::model::TrackData::setXVelocityECEF(), domain::model::TrackData::setYPositionECEF(), domain::model::TrackData::setYVelocityECEF(), domain::model::TrackData::setZPositionECEF(), domain::model::TrackData::setZVelocityECEF(), and validTrackData_.
Member Data Documentation
validTrackData_
TrackData TrackDataTest::validTrackData_ protected
Definition at line 36 of file TrackDataTest.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
/workspaces/hexagon_c/test/a_hexagon/test/a_hexagon/domain/model/TrackDataTest.cpp