a_hexagon: Logger Class Reference
Logger Class Reference
#include <Logger.hpp>
Public Member Functions
void initialize (const std::string &name="a_hexagon", const std::string &logFile="", bool async=true)
void shutdown () noexcept
bool isInitialized () const noexcept
template<typename... Args>
void info (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
void debug (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
void warn (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
void error (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
void critical (spdlog::format_string_t< Args... > fmt, Args &&... args)
template<typename... Args>
void trace (spdlog::format_string_t< Args... > fmt, Args &&... args)
Static Public Member Functions
static Logger & getInstance () noexcept
Private Member Functions
Logger ()=default
~Logger ()=default
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
Detailed Description
Definition at line 260 of file Logger.hpp.
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger () private default
~Logger()
Logger::~Logger () private default
Logger() [2/2]
Logger::Logger (const Logger &) private delete
Member Function Documentation
critical()
template<typename... Args> void Logger::critical (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 306 of file Logger.hpp.
References utils::Logger::critical().
debug()
template<typename... Args> void Logger::debug (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 291 of file Logger.hpp.
References utils::Logger::debug().
error()
template<typename... Args> void Logger::error (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 301 of file Logger.hpp.
References utils::Logger::error().
getInstance()
static Logger & Logger::getInstance () inline static noexcept
Definition at line 262 of file Logger.hpp.
info()
template<typename... Args> void Logger::info (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 286 of file Logger.hpp.
References utils::Logger::info().
initialize()
void Logger::initialize (const std::string & name = "a_hexagon", const std::string & logFile = "", bool async = true) inline
Definition at line 267 of file Logger.hpp.
References utils::Logger::init(), and utils::Logger::initWithFile().
isInitialized()
bool Logger::isInitialized () const inline noexcept
Definition at line 281 of file Logger.hpp.
References utils::Logger::isInitialized().
operator=()
Logger & Logger::operator= (const Logger &) private delete
shutdown()
void Logger::shutdown () inline noexcept
Definition at line 277 of file Logger.hpp.
References utils::Logger::shutdown().
trace()
template<typename... Args> void Logger::trace (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 311 of file Logger.hpp.
References utils::Logger::trace().
warn()
template<typename... Args> void Logger::warn (spdlog::format_string_t< Args... > fmt, Args &&... args) inline
Definition at line 296 of file Logger.hpp.
References utils::Logger::warn().
The documentation for this class was generated from the following file:
a_hexagon/utils/Logger.hpp